/* English summaries for the knowledge graph (same facts as the Dutch `s` in graph.js — keep both in sync). */
export const S_EN = {
  cel: 'Starting point: a human epithelial cell. The genome sits in the nucleus (plus a small genome in the mitochondria); protein synthesis happens in the cytosol and on the rough ER.',
  virus: 'A virus binds receptors on the cell surface, enters by endocytosis or membrane fusion and releases its genome. What happens next depends on the genome type (Baltimore classes).',
  adeno: 'Double-stranded DNA virus. Its fibres attach to the CAR receptor; uptake occurs via αv integrins and clathrin-mediated endocytosis, and protein VI helps it escape from the endosome. Dynein carries the capsid along microtubules to a nuclear pore, where it docks at Nup214 and disassembles (with help from kinesin-1 and histone H1) so the DNA can enter the nucleus. The genome usually stays episomal; its protein-coding genes are transcribed by the host RNA polymerase II (the VA RNAs by Pol III).',
  lnp: 'mRNA packaged in a lipid nanoparticle is taken up by endocytosis; ionizable lipids help a small fraction escape the endosome (measured for siRNA-LNPs: ~1–2 %). The mRNA contains N1-methylpseudouridine, which reduces innate immune recognition and increases translation. It is translated in the cytosol and does not enter the nucleus.',
  endocytose: 'The plasma membrane invaginates to form a vesicle; as the endosome acidifies, viruses or nanoparticles escape into the cytosol, otherwise they are degraded in the lysosome.',
  baltimore: 'Seven classes based on genome type and how mRNA is made: dsDNA, ssDNA, dsRNA, (+)ssRNA, (−)ssRNA, ssRNA-RT, dsDNA-RT (Baltimore 1971: six classes; class VII was added later).',
  rt: 'Retroviruses such as HIV-1 (which infects e.g. CD4⁺ T cells and macrophages) copy their single-stranded RNA genome into double-stranded DNA with reverse transcriptase.',
  integratie: 'The viral integrase processes the viral DNA and inserts it into a host chromosome; this provirus is then transcribed like an ordinary gene.',
  kernimport: 'Nuclear pore complex built from ~30 different nucleoporins in multiple copies; a human nucleus (e.g. HeLa) has ~3,000 of them. Cargo carrying an NLS is imported by importin α/β; the RanGTP gradient (high in the nucleus) sets the direction.',
  kern: 'Surrounded by a double nuclear envelope (outer membrane continuous with the ER, lined inside by the nuclear lamina) with nuclear pores. Contains chromatin and the nucleolus (ribosome production).',
  nucleolus: 'Nuclear body around the rDNA repeats where RNA polymerase I makes the rRNA precursor and ribosomal subunits are assembled.',
  chromosoom: 'Human: 46 chromosomes (23 pairs) in a diploid somatic cell; haploid genome ≈3.0–3.1 billion bp (T2T reference: 3.05 Gb), ~2 m of DNA per cell in total.',
  chromatine: 'DNA + proteins. Euchromatin is open and active, heterochromatin compact and mostly silent. Loops and domains (TADs) are formed by, among others, cohesin and CTCF.',
  nucleosoom: '~147 bp of DNA wrapped in about 1.7 left-handed superhelical turns around a histone octamer (2× H2A, H2B, H3, H4). Linker DNA and histone H1 connect consecutive nucleosomes.',
  histonmod: 'Chemical marks on histone tails. Acetylation is associated with open chromatin; methylation is context-dependent (H3K4me3 active, H3K9me3/H3K27me3 repressive).',
  dnamethyl: 'In mammals mainly 5-methylcytosine in CpG dinucleotides. DNMT3A/B add new methyl groups, DNMT1 maintains the pattern after replication. Promoter methylation goes together with silencing.',
  gen: "Promoter, 5' UTR, exons and introns, 3' UTR with polyadenylation signal; regulatory enhancers/silencers can lie far away.",
  dnahelix: 'Two antiparallel strands with the sugar–phosphate backbone outside and paired bases inside. The major and minor grooves give proteins access to the bases.',
  dnavormen: "B-DNA: right-handed, ~10.5 bp/turn in solution (10 in the classic fibre model), 3.4 Å per bp, ~20 Å wide, C2'-endo. A-DNA: right-handed, ~11 bp/turn, shorter and thicker (wider), phosphates closer together, C3'-endo, inclined base pairs (typical of dsRNA and RNA–DNA hybrids). Z-DNA: left-handed, 12 bp/turn, zigzag backbone, alternating syn (G) and anti (C), in alternating (CG)n.",
  noncanon: 'Guanine-rich sequences can form G-quadruplexes (stacked G-quartets with Hoogsteen H-bonds, stabilised by a central cation, K⁺ > Na⁺); in addition triplex DNA (H-DNA), cruciforms at palindromes and i-motifs in C-rich strands.',
  basenparing: 'Watson–Crick: A–T with 2 and G–C with 3 hydrogen bonds. Alternative pairings (Hoogsteen, G–U wobble in RNA) enable other structures.',
  nucleotide: "Base + (deoxy)ribose + phosphate. Purines A and G, pyrimidines C and T (U in RNA). Phosphodiester bonds give the strand a 5'→3' direction.",
  supercoiling: 'Torsional stress in DNA. Topoisomerase I cuts one strand, topoisomerase II both (ATP-dependent). Replication and transcription create positive supercoils ahead of the machinery.',
  replicatie: 'Semi-conservative (Meselson–Stahl, 1958). Starts at many origins per eukaryotic chromosome during S phase.',
  replisoom: 'CMG helicase (Cdc45–MCM2-7–GINS), Pol α-primase, DNA polymerases (ε mainly leading, δ lagging strand), sliding clamp PCNA, RPA, ligase. The lagging strand is made as Okazaki fragments.',
  ssdna: 'Transiently present during replication and repair; protected by binding proteins (RPA in eukaryotes, SSB in bacteria).',
  telomeren: 'Repeats (TTAGGG in vertebrates) at chromosome ends; telomerase is a reverse transcriptase carrying its own RNA template.',
  herstel: 'Base excision (BER), nucleotide excision (NER), mismatch repair (MMR), and for double-strand breaks homologous recombination (HR) or non-homologous end joining (NHEJ).',
  mutaties: 'Point mutations (silent, missense, nonsense), insertions/deletions (frameshift). The effect shows up in protein sequence and structure.',
  genregulatie: 'Transcription factors bind enhancers and promoters; co-activators (e.g. Mediator) and chromatin accessibility decide whether RNA polymerase II starts.',
  promoter: 'Core promoter elements (e.g. TATA box, Inr) bind the general transcription factors TFIID (with TBP), -A, -B, -E, -F, -H. TFIIH opens the DNA and phosphorylates Ser5 of the CTD.',
  rnapol: '12 subunits (Rpb1–12). The C-terminal domain (CTD) of Rpb1 consists of YSPTSPS repeats (52 in humans) whose phosphorylation pattern recruits the processing machinery. Note: PDB 1I6H is yeast Pol II lacking Rpb4/7 (10 subunits); 5FLM is a transcribing mammalian Pol II complex.',
  transcriptie: "RNA polymerase reads the template strand 3'→5' and makes RNA 5'→3' in a transcription bubble; behind the polymerase the DNA helix closes again.",
  operon: 'The sigma factor recognises the −35 and −10 (Pribnow) boxes. Genes in an operon are transcribed together; transcription and translation are coupled because there is no nucleus.',
  polymerasen: 'Humans have three nuclear RNA polymerases: Pol I makes the 47S rRNA precursor (→ 18S, 5.8S, 28S), Pol II makes mRNA and most snRNAs and miRNAs, Pol III makes e.g. tRNA, 5S rRNA and U6 snRNA.',
  rnaprocessing: "The pre-mRNA is processed while it is still being transcribed: 5' cap, removal of introns by the spliceosome, cleavage and polyadenylation of the 3' end. The Pol II CTD brings the enzymes to the site. Only the mature mRNP is exported.",
  capping:"Shortly after initiation the pre-mRNA receives a 7-methylguanosine linked via a 5'–5' triphosphate bridge. Protects against degradation and is required for export and translation initiation.",
  splicing: 'snRNPs (U1, U2, U4, U5, U6) remove introns (mostly GU…AG) via two transesterifications involving the branch-point A; the intron is released as a lariat. Alternative splicing yields several proteins per gene.',
  polya: 'CPSF recognises the AAUAAA signal (via CPSF30 and WDR33) and CstF a GU-rich element further downstream; CPSF73 cleaves ~10–30 nt after the signal and poly(A) polymerase adds a tail of ~200–250 A (later gradually shortened in the cytoplasm by deadenylation).',
  editing: 'The sequence is changed after transcription: A→I by ADAR, C→U by APOBEC1 (e.g. apolipoprotein B).',
  export: 'The mature mRNP is moved through the nuclear pore via TREX and the export receptor NXF1–NXT1 (largely Ran-independent).',
  nmd: 'Quality control: a stop codon lying more than 50–55 nt upstream of the last exon–exon junction leaves an exon junction complex behind the ribosome; this signals a faulty mRNA, which is then degraded.',
  rnai: 'pri-miRNA → Drosha/DGCR8 → pre-miRNA → Exportin-5 → Dicer → RISC with Argonaute; represses translation or cleaves the target mRNA.',
  mrnaafbraak: "Usually deadenylation, then decapping (DCP2) and 5'→3' decay by XRN1, or 3'→5' by the exosome.",
  rnastructuur: "Single-stranded but folds back on itself: hairpins, bulges, pseudoknots. The 2'-OH makes RNA more reactive and forces double-stranded stretches into the A form.",
  translatie: "Ribosomes read the mRNA 5'→3' in codons and link amino acids via peptide bonds; several ribosomes at once form a polysome.",
  ribosoom: 'Eukaryotic 80S (40S + 60S), bacterial 70S (30S + 50S). A, P and E sites. The peptidyl transferase activity resides in the rRNA: the ribosome is a ribozyme.',
  ribogenese: 'The rRNA precursor is cleaved and modified in the nucleolus, assembled with ~80 ribosomal proteins and exported as separate subunits.',
  codon: '64 codons: 61 encode amino acids, 3 are stop codons (UAA, UAG, UGA). AUG = start (Met). Degenerate; wobble at the third codon position.',
  trna: '~76 nt; cloverleaf in 2D, L shape in 3D. Anticodon at one end, CCA end carrying the amino acid at the other, about 75 Å away.',
  aars: 'Attach each amino acid to the correct tRNAs in an ATP-dependent reaction; two structural classes (I and II), often with proofreading activity.',
  initiatie: "Eukaryotes: the 43S pre-initiation complex (40S + eIF2–GTP–Met-tRNAi + eIF1, eIF1A, eIF3, eIF5) binds the cap via eIF4F; once bound to the mRNA it is called the 48S complex, which scans 5'→3' to the start AUG (Kozak context). The 60S then joins (eIF5B). Bacteria: the Shine–Dalgarno sequence pairs with 16S rRNA.",
  elongatie: 'eEF1A (EF-Tu) delivers aminoacyl-tRNA to the A site; peptide bond formation in the ribosome; eEF2 (EF-G) moves the ribosome by one codon.',
  terminatie: 'eRF1 recognises all three stop codons (bacteria: RF1 for UAA/UAG, RF2 for UAA/UGA); the peptide is released and the ribosome recycled.',
  seleno: "Recoding of stop codons: UGA → selenocysteine thanks to a SECIS element (in the 3' UTR in eukaryotes and archaea, just downstream of the UGA in bacteria); UAG → pyrrolysine in some archaea (methanogens) and a few bacteria.",
  er: 'An N-terminal signal peptide is recognised by SRP; the ribosome docks onto the Sec61 translocon and the protein is inserted into the ER lumen or membrane during translation.',
  aminozuren: 'Cα with amino group, carboxyl group, H and a variable side chain (R). Grouping: hydrophobic, polar/hydrophilic, charged (+/−). Name plus three- and one-letter code are exam material.',
  peptide: 'Amide bond (condensation, water released). Flat (planar) and rigid; rotation only around N–Cα (φ) and Cα–C (ψ). Glycine (achiral) and proline (cyclic) are exceptions.',
  primair: 'The amino acid sequence from N- to C-terminus; ultimately determines the 3D structure.',
  secundair: 'Local 3D structure through backbone hydrogen bonds: α-helix (i→i+4, 3.6 residues/turn), 3₁₀ and π helices, β-strands/sheets (parallel, antiparallel, mixed), loops.',
  ramachandran: 'Plot of φ against ψ per residue; shows allowed regions (α-helix around −60/−45, β around −120/+120) and outliers caused by steric hindrance.',
  tertiair: 'Global fold of a single chain, stabilised by the hydrophobic effect, hydrogen bonds, salt bridges, disulfide bridges and ligands. Intermediate level: supersecondary structures (helix-turn-helix, Greek key, Rossmann fold…) and domains.',
  quaternair: 'Several chains (protomers) together: homo- or heteromer. Course example: haemoglobin, an α2β2 heterotetramer.',
  vouwing: 'The sequence contains the information for the native structure (Anfinsen). Folding proceeds down an energy funnel, often already co-translationally, in µs to s (Levinthal paradox).',
  chaperones: 'Hsp70 (and trigger factor in bacteria) protects nascent chains; chaperonins (GroEL/GroES, TRiC/CCT) provide an enclosed folding chamber.',
  ptm: 'Phosphorylation (Ser/Thr/Tyr), glycosylation, methylation, acetylation, ubiquitination, hydroxylation (e.g. hydroxyproline in collagen).',
  glyco: 'In the ER, oligosaccharyltransferase transfers a preassembled sugar tree onto Asn in the motif N-X-S/T (X ≠ Pro); further processed in the Golgi.',
  disulfide: 'Covalent S–S bond between two cysteines, formed in the oxidising environment of the ER with the help of PDI.',
  golgi: 'Vesicles from ER to Golgi; sorting to plasma membrane, secretion or lysosome.',
  ubiquitine: 'An E1–E2–E3 cascade attaches ubiquitin chains; K48-linked chains target the protein to the 26S proteasome for degradation.',
  misvouwing: 'Misfolded proteins can aggregate into amyloid fibrils (cross-β); involved in e.g. Alzheimer’s and Parkinson’s disease.',
  idp: 'Proteins or regions without a fixed structure that only become ordered upon binding or under certain conditions (last chapter of the course).',
};

export const SCALES_EN = {
  1: 'Cell & organism', 2: 'Organelle & compartment', 3: 'Macromolecular complex', 4: 'Molecule & fold', 5: 'Atomic',
};
