/* Lokale kopieën van PDB-bestanden (data/pdb/), zodat de app ook zonder toegang tot RCSB werkt (bv. online gepubliceerd).
 * pdbUrl('1KX5', 'cif') → lokaal bestand als het in de lijst staat, anders de RCSB-download.
 * rcsbEntryUrl('1KX5')  → lokale kopie van de RCSB-metadata (JSON) of de REST-API. */
const LOCAL = new Set([
  '143D.json',
  '143D.pdb',
  '1AIO.json',
  '1AIO.pdb',
  '1ANR.json',
  '1ANR.pdb',
  '1BBB.cif',
  '1BBB.pdb',
  '1BNA.json',
  '1BNA.pdb',
  '1BWG.json',
  '1BWG.pdb',
  '1D11.json',
  '1D11.pdb1',
  '1DCG.json',
  '1DCG.pdb',
  '1DCW.json',
  '1DCW.pdb',
  '1EHZ.json',
  '1EHZ.pdb',
  '1EL2.json',
  '1EL2.pdb',
  '1J5E.json',
  '1J5E.pdb',
  '1JMC.json',
  '1JMC.pdb',
  '1KF1.json',
  '1KF1.pdb',
  '1KX5.cif',
  '1KX5.json',
  '1KX5.pdb',
  '1QBJ.json',
  '1QBJ.pdb',
  '1RNA.json',
  '1RNA.pdb',
  '1U6B.json',
  '1U6B.pdb',
  '1UBQ.pdb',
  '1Y26.json',
  '1Y26.pdb',
  '1YMO.json',
  '1YMO.pdb',
  '2OEU.json',
  '2OEU.pdb',
  '3Q1Q.json',
  '3Q1Q.pdb',
  '437D.json',
  '437D.pdb',
  '440D.json',
  '440D.pdb',
  '479D.json',
  '479D.pdb',
  '4PJO.json',
  '4PJO.pdb',
  '4W5N.json',
  '4W5N.pdb',
  '5FLM.cif',
  '6BNA.json',
  '6BNA.pdb',
]);
const here = f => new URL(`../data/pdb/${f}`, import.meta.url).href;
export const pdbUrl = (id, ext = 'pdb') => LOCAL.has(`${id}.${ext}`) ? here(`${id}.${ext}`) : `https://files.rcsb.org/download/${id}.${ext}`;
export const rcsbEntryUrl = id => LOCAL.has(`${id}.json`) ? here(`${id}.json`) : `https://data.rcsb.org/rest/v1/core/entry/${id}`;
