/* Uitleg per knoop voor stage 'entry' — zie app/SCENES.md */
export default {

  cel: {
    nl: {
      what: 'Het verhaal begint in een menselijke epitheelcel van ongeveer 20 µm. Het grootste deel van het genoom ligt in de celkern (5–10 µm), afgeschermd door een dubbele kernenvelop met kernporiën; mitochondriën hebben daarnaast hun eigen kleine genoom. Eiwitten worden gemaakt in het cytosol en aan het ruwe endoplasmatisch reticulum. Alles wat in deze app volgt — transcriptie, RNA-bewerking, translatie en vouwing — speelt zich in deze ene cel af.',
      how: [
        'Het plasmamembraan scheidt het cytosol van de buitenwereld en bepaalt wat binnenkomt.',
        'Genetische informatie van buitenaf (een virus, een mRNA-nanodeeltje) wordt meestal via endocytose opgenomen.',
        'DNA moet de kern in om afgelezen te worden; dat kan alleen door een kernporiecomplex.',
        'In de kern schrijft RNA-polymerase II genen over naar pre-mRNA, dat meteen wordt bewerkt.',
        'Het rijpe mRNA verlaat de kern via dezelfde poriën en komt in het cytosol.',
        'Vrije ribosomen en ribosomen op het ruwe ER vertalen het mRNA naar een eiwitketen.',
        'De keten vouwt, wordt eventueel gemodificeerd, doet zijn werk en wordt uiteindelijk afgebroken.',
      ],
      facts: [['Celdiameter', 'typisch 10–30 µm (HeLa ≈ 20 µm)'], ['Kerndiameter', '≈ 5–10 µm'], ['Kernporiën per kern', '≈ 3 000 (HeLa); band 2 000–5 000 bij gewervelden'],
        ['Haploïd genoom', '≈ 3,0–3,1 miljard basenparen'], ['DNA per cel', 'ruwweg 2 meter, opgevouwen in een kern van µm-formaat'], ['Mitochondriaal genoom', '16 569 bp (humaan referentiegenoom)']],
      why: 'Alle schaalniveaus in deze app horen bij deze ene cel: van 20 µm (cel) via 120 nm (kernporie) en 25 nm (ribosoom) tot 0,34 nm (afstand tussen twee basenparen). Door telkens in te zoomen blijft duidelijk waar in de cel elke stap gebeurt.',
    },
    en: {
      what: 'The story starts in a human epithelial cell of about 20 µm. Most of the genome sits in the nucleus (5–10 µm), shielded by a double nuclear envelope with nuclear pores; mitochondria also carry their own small genome. Proteins are made in the cytosol and on the rough endoplasmic reticulum. Everything that follows in this app — transcription, RNA processing, translation and folding — happens inside this one cell.',
      how: [
        'The plasma membrane separates the cytosol from the outside world and controls what gets in.',
        'Genetic information from outside (a virus, an mRNA nanoparticle) is usually taken up by endocytosis.',
        'DNA has to reach the nucleus to be read, and can only do so through a nuclear pore complex.',
        'In the nucleus RNA polymerase II copies genes into pre-mRNA, which is processed as it is made.',
        'The mature mRNA leaves the nucleus through the same pores and reaches the cytosol.',
        'Free ribosomes and ribosomes on the rough ER translate the mRNA into a protein chain.',
        'The chain folds, may be modified, does its job and is eventually degraded.',
      ],
      facts: [['Cell diameter', 'typically 10–30 µm (HeLa ≈ 20 µm)'], ['Nuclear diameter', '≈ 5–10 µm'], ['Nuclear pores per nucleus', '≈ 3,000 (HeLa); range 2,000–5,000 in vertebrates'],
        ['Haploid genome', '≈ 3.0–3.1 billion base pairs'], ['DNA per cell', 'roughly 2 metres, folded into a nucleus of µm size'], ['Mitochondrial genome', '16,569 bp (human reference genome)']],
      why: 'Every zoom level in this app belongs to this one cell: from 20 µm (cell) via 120 nm (nuclear pore) and 25 nm (ribosome) down to 0.34 nm (rise per base pair). Zooming in step by step keeps it clear where in the cell each step happens.',
    },
    sources: [
      { t: 'Milo & Phillips, Cell Biology by the Numbers — How big is a human cell? / How big are nuclei?', url: 'https://book.bionumbers.org/how-big-is-a-human-cell/' },
      { t: 'Alberts et al., Molecular Biology of the Cell (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK21054/' },
      { t: 'Nurk et al., The complete sequence of a human genome. Science 2022 (T2T-CHM13)', url: 'https://www.science.org/doi/10.1126/science.abj6987' },
      { t: 'Ori et al., Cell type-specific nuclear pores. Mol Syst Biol 2013 (aantallen NPC per kern)', url: 'https://www.embopress.org/doi/full/10.1038/msb.2013.4' },
    ],
  },

  virus: {
    nl: {
      what: 'Een virus is een genoom in een eiwitjas (capside), soms omhuld door een membraan uit de vorige gastheercel. Het bezit geen ribosomen en geen eigen energievoorziening: om zich te vermenigvuldigen moet het zijn genoom in een cel krijgen en de machinerie van die cel gebruiken. Welke cellen besmet kunnen worden (het tropisme) hangt af van welke receptoren het virus herkent.',
      how: [
        'Aanhechting: eiwitten op het virusoppervlak binden een receptor (eiwit of suiker) op de gastheercel.',
        'Binnenkomst route A — endocytose: de cel neemt het deeltje op in een blaasje; het virus moet daar later uit ontsnappen.',
        'Binnenkomst route B — membraanfusie: alleen omhulde virussen kunnen hun envelop met een celmembraan laten fuseren.',
        'Uncoating: het capside valt (deels) uiteen en het genoom komt vrij.',
        'Transport: DNA-virussen moeten meestal naar de kern, RNA-virussen blijven meestal in het cytosol.',
        'Expressie en replicatie: de gastheercel maakt virale eiwitten; het genoom wordt gekopieerd (welke route hangt af van de Baltimore-klasse).',
        'Assemblage en vrijgave: nieuwe deeltjes ontstaan en komen vrij door lysis of door knopvorming aan een membraan.',
      ],
      facts: [['Grootte virusdeeltje', '≈ 20–300 nm (adenovirus ≈ 90 nm, HIV-1 ≈ 100–120 nm)'], ['Klathrine-blaasje', '≈ 100 nm — daarom past een virus er net in'],
        ['Twee binnenkomstroutes', 'endocytose (omhuld en niet-omhuld) of directe fusie (alleen omhuld)'], ['Bepaalt het tropisme', 'de receptor, niet het virus alleen'], ['Baltimore-klassen', '7, op basis van de weg naar mRNA']],
      why: 'Virussen zijn het natuurlijke bewijs dat het centrale dogma universeel is: ze hebben geen eigen ribosomen en moeten hun informatie dus in de taal van de cel aanleveren. Daarom zijn ze ook zulke goede gereedschappen (vectoren) én zulke goede leermiddelen om de weg van DNA naar eiwit te volgen.',
    },
    en: {
      what: 'A virus is a genome in a protein coat (capsid), sometimes wrapped in a membrane taken from the previous host cell. It has no ribosomes and no energy metabolism of its own: to multiply it must get its genome into a cell and borrow that cell’s machinery. Which cells can be infected (the tropism) depends on which receptors the virus recognises.',
      how: [
        'Attachment: proteins on the virus surface bind a receptor (protein or sugar) on the host cell.',
        'Entry route A — endocytosis: the cell takes the particle up in a vesicle, which the virus must later escape.',
        'Entry route B — membrane fusion: only enveloped viruses can fuse their envelope with a cell membrane.',
        'Uncoating: the capsid (partly) falls apart and the genome is released.',
        'Transport: DNA viruses usually have to reach the nucleus, RNA viruses usually stay in the cytosol.',
        'Expression and replication: the host cell makes viral proteins; the genome is copied (the route depends on the Baltimore class).',
        'Assembly and release: new particles form and are released by lysis or by budding at a membrane.',
      ],
      facts: [['Virion size', '≈ 20–300 nm (adenovirus ≈ 90 nm, HIV-1 ≈ 100–120 nm)'], ['Clathrin-coated vesicle', '≈ 100 nm — which is just big enough for a virus'],
        ['Two entry routes', 'endocytosis (enveloped and non-enveloped) or direct fusion (enveloped only)'], ['Sets the tropism', 'the receptor, not the virus alone'], ['Baltimore classes', '7, based on the route to mRNA']],
      why: 'Viruses are the natural proof that the central dogma is universal: having no ribosomes of their own, they must deliver their information in the language of the cell. That is why they are such useful tools (vectors) and such good teaching examples for following the road from DNA to protein.',
    },
    sources: [
      { t: 'Alberts et al., Molecular Biology of the Cell (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK21054/' },
      { t: 'Koonin et al., The Baltimore Classification of Viruses 50 Years Later. Microbiol Mol Biol Rev 2021', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8483701/' },
      { t: 'Kremer & Nemerow, Adenovirus Tales: From the Cell Surface to the Nuclear Pore Complex. PLoS Pathog 2015', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4456001/' },
      { t: 'ViralZone (SIB Swiss Institute of Bioinformatics) — virusfamilies, afmetingen en replicatiecycli', url: 'https://viralzone.expasy.org/' },
    ],
  },

  adeno: {
    nl: {
      what: 'Humaan adenovirus C5 (HAdV-C5) is een niet-omhuld virus met een icosaëdrisch capside van ongeveer 90 nm en een lineair dubbelstrengig DNA-genoom van ongeveer 36 kb (Baltimore-klasse I). Het capside bestaat uit 240 hexonen (de vlakken) en 12 pentonbasissen (de hoeken), elk met een uitstekende vezel met een knop. Het virus gebruikt twee verschillende oppervlakte-eiwitten om zich vast te hechten en om opgenomen te worden, en levert zijn DNA uiteindelijk af aan een kernporie.',
      how: [
        'De vezelknop bindt CAR (coxsackie- en adenovirusreceptor) op het epitheeloppervlak: dat is aanhechting, nog geen opname.',
        'Een RGD-motief op de pentonbasis bindt αvβ3/αvβ5-integrines; dat signaal start klathrine-gemedieerde endocytose en maakt de hoeken van het capside al losser.',
        'Dynamine knijpt het blaasje af; in het endosoom komt het membraanlytische proteïne VI vrij, dat het endosoommembraan openbreekt.',
        'Het deels ontmantelde capside komt in het cytosol en wordt door dyneïne over microtubuli naar de kern getrokken.',
        'Aan de kernporie dokt het capside met hexon aan de nucleoporine Nup214.',
        'Kinesine-1 (zware keten Kif5C via Nup358, lichte keten op het capside) trekt het capside uit elkaar; ook histon H1 is nodig voor de ontmanteling.',
        'Het genoom gaat samen met het virale kerneiwit VII de kern in en blijft daar episomaal — het integreert niet in het gastheergenoom.',
        'RNA-polymerase II van de cel schrijft de eiwitcoderende genen af (eerst E1A); de VA-RNA\'s worden door RNA-polymerase III gemaakt.',
      ],
      facts: [['Capside', '≈ 90 nm, 240 hexonen + 12 pentonbasissen'], ['Genoom', 'lineair dsDNA van ≈ 36 kb, verpakt met proteïne VII'],
        ['Aanhechting', 'vezelknop ↔ CAR'], ['Opname', 'penton-RGD ↔ αvβ3/αvβ5-integrine → klathrine-endocytose'],
        ['Endosomale ontsnapping', 'proteïne VI (amfipathische helix)'], ['Docking aan de porie', 'hexon ↔ Nup214']],
      why: 'Dit is hoofdstuk 2 van het hoofdverhaal: het adenovirus levert vreemd DNA af op precies de plaats waar het eigen genoom van de cel ligt. Omdat het genoom episomaal blijft en toch door Pol II wordt afgelezen, is het een perfecte gids voor de rest van het verhaal — én de reden waarom adenovirale vectoren in gentherapie en vaccins gebruikt worden.',
    },
    en: {
      what: 'Human adenovirus C5 (HAdV-C5) is a non-enveloped virus with an icosahedral capsid of about 90 nm and a linear double-stranded DNA genome of about 36 kb (Baltimore class I). The capsid is built from 240 hexons (the faces) and 12 penton bases (the vertices), each carrying a protruding fibre with a knob. The virus uses two different surface proteins for attachment and for uptake, and finally delivers its DNA to a nuclear pore.',
      how: [
        'The fibre knob binds CAR (coxsackievirus and adenovirus receptor) at the epithelial surface: that is attachment, not yet uptake.',
        'An RGD motif on the penton base binds αvβ3/αvβ5 integrins; this signal triggers clathrin-mediated endocytosis and already loosens the capsid vertices.',
        'Dynamin pinches off the vesicle; inside the endosome the membrane-lytic protein VI is released and ruptures the endosomal membrane.',
        'The partly disassembled capsid reaches the cytosol and is pulled towards the nucleus by dynein along microtubules.',
        'At the nuclear pore the capsid docks onto the nucleoporin Nup214 via hexon.',
        'Kinesin-1 (heavy chain Kif5C via Nup358, light chain on the capsid) pulls the capsid apart; histone H1 is also required for disassembly.',
        'The genome enters the nucleus together with the viral core protein VII and stays episomal there — it does not integrate into the host genome.',
        'The cell’s own RNA polymerase II transcribes the protein-coding genes (E1A first); the VA RNAs are made by RNA polymerase III.',
      ],
      facts: [['Capsid', '≈ 90 nm, 240 hexons + 12 penton bases'], ['Genome', 'linear dsDNA of ≈ 36 kb, packaged with protein VII'],
        ['Attachment', 'fibre knob ↔ CAR'], ['Uptake', 'penton RGD ↔ αvβ3/αvβ5 integrin → clathrin endocytosis'],
        ['Endosomal escape', 'protein VI (amphipathic helix)'], ['Docking at the pore', 'hexon ↔ Nup214']],
      why: 'This is chapter 2 of the main story: the adenovirus delivers foreign DNA exactly where the cell keeps its own genome. Because that genome stays episomal and is still read by Pol II, it is a perfect guide for the rest of the story — and the reason adenoviral vectors are used in gene therapy and vaccines.',
    },
    sources: [
      { t: 'Kremer & Nemerow, Adenovirus Tales: From the Cell Surface to the Nuclear Pore Complex. PLoS Pathog 2015;11:e1004821', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4456001/' },
      { t: 'Trotman et al., Import of adenovirus DNA involves the nuclear pore complex receptor CAN/Nup214 and histone H1. Nat Cell Biol 2001', url: 'https://www.nature.com/articles/ncb1201-1092' },
      { t: 'Strunze et al., Kinesin-1-mediated capsid disassembly… Cell Host Microbe 2011;10:210–23', url: 'https://pubmed.ncbi.nlm.nih.gov/21925109/' },
      { t: 'Cassany et al., Nuclear import of adenovirus DNA involves direct interaction of hexon with Nup214. J Virol 2015', url: 'https://journals.asm.org/doi/full/10.1128/jvi.02639-14' },
      { t: 'RCSB PDB-101, Molecule of the Month: Adenovirus (structuren 6B1T, 1KAC, 1QIU)', url: 'https://pdb101.rcsb.org/motm/132' },
    ],
  },

  lnp: {
    nl: {
      what: 'Een mRNA-vaccin bestaat uit boodschapper-RNA verpakt in een lipidenanodeeltje (LNP) van ongeveer 80–100 nm. Het deeltje bevat vier soorten lipiden: een ioniseerbaar lipide dat het negatief geladen mRNA bindt, een helperfosfolipide, cholesterol en een PEG-lipide. Het mRNA wordt in het cytosol vertaald tot een antigeen; het komt de kern niet in en kan niet in het genoom terechtkomen.',
      how: [
        'Het LNP wordt via endocytose opgenomen (onder andere na binding van ApoE aan lipoproteïnereceptoren).',
        'Het endosoom verzuurt door de v-ATPase; de pH zakt van ≈ 7,4 naar ≈ 6,5 en verder naar ≈ 5,5.',
        'De ioniseerbare lipiden (schijnbare pKa ongeveer 6–6,7) zijn neutraal in het bloed maar raken in het zure endosoom geprotoneerd en dus positief geladen.',
        'Die positieve lading bindt de negatief geladen binnenkant van het endosoommembraan; het membraan destabiliseert lokaal.',
        'Een kleine fractie van het mRNA ontsnapt daardoor naar het cytosol; de rest gaat met het endosoom naar het lysosoom.',
        'In het cytosol binden ribosomen de 5\'-cap en beginnen ze de translatie: het antigeen wordt gemaakt.',
        'Het antigeen wordt gepresenteerd en/of uitgescheiden, waarna het immuunsysteem er antistoffen en T-cellen tegen maakt.',
        'Het mRNA wordt daarna gewoon door de cel afgebroken; het verdwijnt binnen enkele dagen.',
      ],
      facts: [['Deeltjesgrootte', '≈ 80–100 nm'], ['Lipiden', 'ioniseerbaar lipide + helperfosfolipide + cholesterol + PEG-lipide'],
        ['Endosomale ontsnapping', 'orde van grootte enkele procenten (1–2 % gemeten met siRNA-LNP\'s, Gilleron 2013)'],
        ['Modificatie', 'alle uridines vervangen door N1-methylpseudouridine (m1Ψ)'], ['Effect van m1Ψ', 'minder aangeboren immuunherkenning (TLR/RIG-I) én meer eiwitopbrengst'],
        ['Kern', 'niet betrokken: geen import, geen reverse transcriptase, geen integratie']],
      why: 'Het mRNA-vaccin is de spiegel van de virusroute: het slaat de hele kern-stap over en begint meteen bij de translatie. Naast elkaar laten de twee routes precies zien welke stappen van DNA naar eiwit noodzakelijk zijn en welke niet.',
    },
    en: {
      what: 'An mRNA vaccine consists of messenger RNA packaged in a lipid nanoparticle (LNP) of about 80–100 nm. The particle contains four kinds of lipid: an ionizable lipid that binds the negatively charged mRNA, a helper phospholipid, cholesterol and a PEG-lipid. The mRNA is translated into an antigen in the cytosol; it does not enter the nucleus and cannot end up in the genome.',
      how: [
        'The LNP is taken up by endocytosis (among other routes after ApoE binds lipoprotein receptors).',
        'The endosome is acidified by the v-ATPase; the pH drops from ≈ 7.4 to ≈ 6.5 and further to ≈ 5.5.',
        'The ionizable lipids (apparent pKa around 6–6.7) are neutral in the blood but become protonated, and thus positively charged, in the acidic endosome.',
        'That positive charge binds the negatively charged inner leaflet of the endosomal membrane, which destabilises locally.',
        'A small fraction of the mRNA escapes into the cytosol; the rest travels with the endosome to the lysosome.',
        'In the cytosol ribosomes bind the 5\' cap and start translation: the antigen is made.',
        'The antigen is presented and/or secreted, after which the immune system raises antibodies and T cells against it.',
        'The mRNA is then simply degraded by the cell and disappears within a few days.',
      ],
      facts: [['Particle size', '≈ 80–100 nm'], ['Lipids', 'ionizable lipid + helper phospholipid + cholesterol + PEG-lipid'],
        ['Endosomal escape', 'order of a few per cent (1–2 % measured with siRNA-LNPs, Gilleron 2013)'],
        ['Modification', 'every uridine replaced by N1-methylpseudouridine (m1Ψ)'], ['Effect of m1Ψ', 'less innate immune sensing (TLR/RIG-I) and higher protein yield'],
        ['Nucleus', 'not involved: no import, no reverse transcriptase, no integration']],
      why: 'The mRNA vaccine mirrors the viral route: it skips the whole nuclear stage and starts directly at translation. Side by side, the two routes show exactly which steps from DNA to protein are strictly necessary and which are not.',
    },
    sources: [
      { t: 'Gilleron et al., Image-based analysis of lipid nanoparticle-mediated siRNA delivery… Nat Biotechnol 2013;31:638–46', url: 'https://www.nature.com/articles/nbt.2612' },
      { t: 'Endosomal escape: a bottleneck for LNP-mediated therapeutics. PNAS 2023', url: 'https://www.pnas.org/doi/10.1073/pnas.2307800120' },
      { t: 'Mechanisms of innate and adaptive immunity to the BNT162b2 vaccine (m1Ψ). Nat Immunol 2022', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8989677/' },
      { t: 'N1-methylpseudouridine modification level correlates with protein expression, immunogenicity and stability of mRNA', url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11406044/' },
    ],
  },

  endocytose: {
    nl: {
      what: 'Endocytose is de manier waarop een cel materiaal van buiten naar binnen haalt: een stukje plasmamembraan stulpt naar binnen en snoert af tot een blaasje. De best bestudeerde vorm is klathrine-gemedieerde endocytose, met blaasjes van ongeveer 100 nm. Het blaasje fuseert met een vroeg endosoom, dat geleidelijk verzuurt en tot laat endosoom rijpt; wat niet ontsnapt of gerecycleerd wordt, eindigt in het lysosoom.',
      how: [
        'Adaptoreiwitten (o.a. AP-2) herkennen receptoren met vracht en verzamelen ze in één stukje membraan.',
        'Klathrine-triskelia koppelen aan elkaar tot een gebogen mandje dat het membraan naar binnen dwingt.',
        'De GTPase dynamine vormt een spiraal rond de hals van de put en knijpt die door: het blaasje komt los.',
        'De klathrine-jas valt eraf en het blaasje fuseert met een vroeg endosoom (pH ≈ 6,5).',
        'De v-ATPase pompt protonen naar binnen; bij rijping tot laat endosoom zakt de pH naar ≈ 5,5.',
        'Veel omhulde virussen gebruiken die verzuring als signaal. Het adenovirus niet: mechanische prikkels bij de binding aan receptoren leggen het membraanlytische proteïne VI al vroeg bloot, en dat breekt het membraan open, onafhankelijk van de pH (Wiethoff et al. 2005; Luisoni et al. 2015).',
        'Lipidenanodeeltjes ontsnappen anders: hun ioniseerbare lipiden worden positief en destabiliseren het membraan.',
        'Wat niet ontsnapt, komt in het lysosoom (pH ≈ 4,5) terecht en wordt door zure hydrolasen afgebroken.',
      ],
      facts: [['Klathrine-blaasje', '≈ 100 nm (fagosomen zijn > 250 nm)'], ['Vroeg endosoom', 'pH ≈ 6,5'], ['Laat endosoom', 'pH ≈ 5,5'], ['Lysosoom', 'pH ≈ 4,5'],
        ['Zuurpomp', 'v-ATPase (vacuolair H⁺-ATPase)'], ['Afsnoeren van de hals', 'dynamine, met GTP-hydrolyse']],
      why: 'Dit is het knelpunt van elke aflevering van genetische informatie: binnenkomen is makkelijk, maar uit het blaasje raken is moeilijk. Voor virussen is het een verfijnd mechanisme; voor mRNA-vaccins en gentherapie is het de belangrijkste efficiëntiebeperking.',
    },
    en: {
      what: 'Endocytosis is how a cell brings material inside: a patch of plasma membrane invaginates and pinches off into a vesicle. The best-studied form is clathrin-mediated endocytosis, with vesicles of about 100 nm. The vesicle fuses with an early endosome, which gradually acidifies and matures into a late endosome; whatever does not escape or get recycled ends up in the lysosome.',
      how: [
        'Adaptor proteins (such as AP-2) recognise loaded receptors and gather them into a single membrane patch.',
        'Clathrin triskelia link into a curved cage that forces the membrane inwards.',
        'The GTPase dynamin forms a spiral around the neck of the pit and severs it: the vesicle is released.',
        'The clathrin coat falls off and the vesicle fuses with an early endosome (pH ≈ 6.5).',
        'The v-ATPase pumps protons inside; on maturation into a late endosome the pH falls to ≈ 5.5.',
        'Many enveloped viruses use that acidification as a cue. Adenovirus does not: mechanical cues on receptor binding expose the membrane-lytic protein VI early, and it ruptures the membrane independently of pH (Wiethoff et al. 2005; Luisoni et al. 2015).',
        'Lipid nanoparticles escape differently: their ionizable lipids become positive and destabilise the membrane.',
        'Whatever does not escape reaches the lysosome (pH ≈ 4.5) and is degraded by acid hydrolases.',
      ],
      facts: [['Clathrin-coated vesicle', '≈ 100 nm (phagosomes are > 250 nm)'], ['Early endosome', 'pH ≈ 6.5'], ['Late endosome', 'pH ≈ 5.5'], ['Lysosome', 'pH ≈ 4.5'],
        ['Acidifying pump', 'v-ATPase (vacuolar H⁺-ATPase)'], ['Severing the neck', 'dynamin, using GTP hydrolysis']],
      why: 'This is the bottleneck for any delivery of genetic information: getting in is easy, getting out of the vesicle is hard. For viruses it is a refined mechanism; for mRNA vaccines and gene therapy it is the main limit on efficiency.',
    },
    sources: [
      { t: 'Wiethoff et al. (2005) Adenovirus protein VI mediates membrane disruption following capsid disassembly. J Virol 79:1992', url: 'https://pubmed.ncbi.nlm.nih.gov/15681401/' },
      { t: 'Luisoni et al. (2015) Co-option of membrane wounding enables virus penetration into cells. Cell Host Microbe 18:75', url: 'https://pubmed.ncbi.nlm.nih.gov/26159720/' },
      { t: 'Alberts et al., Transport into the Cell from the Plasma Membrane: Endocytosis (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK26870/' },
      { t: 'Hu et al., The endosomal-lysosomal system: from acidification and cargo sorting to neurodegeneration. Transl Neurodegener 2015', url: 'https://link.springer.com/article/10.1186/s40035-015-0041-1' },
      { t: 'Kremer & Nemerow, Adenovirus Tales (proteïne VI en endosomale ontsnapping). PLoS Pathog 2015', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4456001/' },
      { t: 'Endosomal escape: a bottleneck for LNP-mediated therapeutics. PNAS 2023', url: 'https://www.pnas.org/doi/10.1073/pnas.2307800120' },
    ],
  },

  baltimore: {
    nl: {
      what: 'David Baltimore stelde in 1971 een indeling van virussen voor die niet op verwantschap berust, maar op één praktische vraag: hoe komt dit genoom aan mRNA? Omdat ribosomen alleen (+)mRNA kunnen lezen, moet elk virus daar hoe dan ook uitkomen. Baltimore beschreef zes klassen; met de later toegevoegde klasse VII (dsDNA-RT) zijn het er zeven, en elke klasse zegt meteen welke enzymen het virus zelf moet meebrengen.',
      how: [
        'Klasse I — dsDNA: wordt (meestal in de kern) door RNA-polymerase II van de gastheer afgeschreven. Voorbeelden: adenovirus, herpesvirussen, en het pokkenvirus, dat in het cytoplasma repliceert met zijn eigen RNA-polymerase.',
        'Klasse II — ssDNA: wordt eerst tot dubbelstrengig DNA aangevuld en daarna afgeschreven. Voorbeeld: parvovirus B19.',
        'Klasse III — dsRNA: een cel heeft geen eigen enzym om virus-RNA naar RNA te kopiëren, dus het virus brengt zelf een RNA-afhankelijk RNA-polymerase (RdRp) mee. Voorbeelden: rotavirus, reovirus. (Uitzondering op die regel: het hepatitis-deltavirus laat zijn RNA-genoom kopiëren door het RNA-polymerase II van de gastheer.)',
        'Klasse IV — (+)ssRNA: het genoom heeft dezelfde polariteit als mRNA en kan meteen vertaald worden. Voorbeelden: poliovirus, SARS-CoV-2, hepatitis A.',
        'Klasse V — (−)ssRNA: het genoom is complementair aan mRNA; de RdRp moet in het virusdeeltje aanwezig zijn. Voorbeelden: influenza, rabiës, mazelen, ebola.',
        'Klasse VI — ssRNA-RT: reverse transcriptase maakt dsDNA van het RNA-genoom, dat daarna in het gastheergenoom integreert. Voorbeeld: HIV-1.',
        'Klasse VII — dsDNA-RT: het genoom is DNA, maar de replicatie loopt via een RNA-tussenstap die door reverse transcriptase terug naar DNA wordt geschreven. Voorbeeld: hepatitis B-virus.',
      ],
      facts: [['Voorgesteld door', 'David Baltimore, 1971 (zes klassen)'], ['Aantal klassen', '7 (klasse VII later toegevoegd)'], ['Het criterium', 'de route van het genoom naar (+)mRNA'],
        ['Klassen met eigen polymerase', 'III, V (RdRp) en VI, VII (reverse transcriptase)'], ['Adenovirus', 'klasse I'], ['HIV-1', 'klasse VI']],
      why: 'De indeling is eigenlijk het centrale dogma, toegepast op virussen: ze laat zien dat elke informatiestroom (DNA→RNA, RNA→RNA, RNA→DNA) ergens in de natuur voorkomt, maar dat alles uiteindelijk bij hetzelfde ribosoom uitkomt.',
    },
    en: {
      what: 'In 1971 David Baltimore proposed a classification of viruses that is not based on relatedness but on one practical question: how does this genome get to mRNA? Because ribosomes can only read (+)mRNA, every virus has to end up there. Baltimore described six classes; with the later addition of class VII (dsDNA-RT) there are seven, and each class immediately tells you which enzymes the virus must bring along.',
      how: [
        'Class I — dsDNA: transcribed (usually in the nucleus) by the host RNA polymerase II. Examples: adenovirus, herpesviruses, and poxvirus, which replicates in the cytoplasm using its own RNA polymerase.',
        'Class II — ssDNA: first completed into double-stranded DNA and then transcribed. Example: parvovirus B19.',
        'Class III — dsRNA: a cell has no enzyme of its own to copy viral RNA into RNA, so the virus brings its own RNA-dependent RNA polymerase (RdRp). Examples: rotavirus, reovirus. (Exception to that rule: hepatitis delta virus has its RNA genome copied by the host’s RNA polymerase II.)',
        'Class IV — (+)ssRNA: the genome has the same polarity as mRNA and can be translated immediately. Examples: poliovirus, SARS-CoV-2, hepatitis A.',
        'Class V — (−)ssRNA: the genome is complementary to mRNA; the RdRp must be present inside the virion. Examples: influenza, rabies, measles, Ebola.',
        'Class VI — ssRNA-RT: reverse transcriptase makes dsDNA from the RNA genome, which then integrates into the host genome. Example: HIV-1.',
        'Class VII — dsDNA-RT: the genome is DNA, but replication runs through an RNA intermediate that reverse transcriptase writes back into DNA. Example: hepatitis B virus.',
      ],
      facts: [['Proposed by', 'David Baltimore, 1971 (six classes)'], ['Number of classes', '7 (class VII added later)'], ['The criterion', 'the route from genome to (+)mRNA'],
        ['Classes with their own polymerase', 'III, V (RdRp) and VI, VII (reverse transcriptase)'], ['Adenovirus', 'class I'], ['HIV-1', 'class VI']],
      why: 'The classification is really the central dogma applied to viruses: it shows that every direction of information flow (DNA→RNA, RNA→RNA, RNA→DNA) exists somewhere in nature, but that everything converges on the same ribosome.',
    },
    sources: [
      { t: 'Taylor (2015) Hepatitis D virus replication. Cold Spring Harb Perspect Med 5:a021568 (RNA-polymerase II kopieert het HDV-RNA)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4632862/' },
      { t: 'Koonin et al., The Baltimore Classification of Viruses 50 Years Later. Microbiol Mol Biol Rev 2021;85:e0005321', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8483701/' },
      { t: 'ICTV — International Committee on Taxonomy of Viruses (virustaxonomie)', url: 'https://ictv.global/' },
      { t: 'ViralZone (SIB Swiss Institute of Bioinformatics) — Baltimore-klassen met voorbeelden per familie', url: 'https://viralzone.expasy.org/' },
    ],
  },

  rt: {
    nl: {
      what: 'Retrovirussen zoals HIV-1 dragen hun genetische informatie als RNA, maar bouwen hun erfelijk materiaal in als DNA. Reverse transcriptase (RT) zet het enkelstrengige (+)RNA-genoom om in dubbelstrengig DNA. Hetzelfde enzym doet drie dingen: DNA maken op een RNA-matrijs, DNA maken op een DNA-matrijs, en met zijn RNase H-activiteit het gekopieerde RNA afbreken. HIV-1 infecteert vooral CD4⁺-T-cellen en macrofagen; het proces gebeurt grotendeels nog binnen het capside in het cytoplasma.',
      how: [
        'Een gastheer-tRNA (tRNA-Lys3) hecht aan de primerbindplaats (PBS) van het genoom en levert het vrije 3\'-OH waar RT mee kan starten.',
        'RT verlengt tot het 5\'-uiteinde van het RNA: het korte "minus-strand strong-stop"-DNA met R en U5.',
        'De RNase H-activiteit breekt het gekopieerde R-U5-RNA af, zodat het DNA-uiteinde vrijkomt.',
        'Eerste strengoverdracht: dat DNA-uiteinde bevat een kopie van R en paart daardoor met de R aan het andere uiteinde van het genoom.',
        'RT maakt nu de hele (−)-streng af; RNase H ruimt het RNA op, behalve een purinerijk stukje: de polypurineketen (PPT).',
        'De PPT blijft liggen en dient als primer voor de (+)-streng; die kopieert ook een stukje van het tRNA, waardoor de PBS-sequentie in DNA ontstaat.',
        'tRNA en PPT worden weggeknipt; tweede strengoverdracht: de twee PBS-kopieën paren met elkaar.',
        'Beide strengen worden afgemaakt: het eindproduct is lineair dsDNA met aan beide uiteinden een volledige LTR (U3-R-U5) — langer dan het RNA waarmee begonnen werd.',
      ],
      facts: [['Genoom', '≈ 9,7 kb (+)ssRNA, twee identieke kopieën per virusdeeltje'], ['Primer', 'gastheer-tRNA-Lys3 op de PBS'],
        ['Twee activiteiten van RT', 'polymerase (RNA- én DNA-matrijs) en RNase H'], ['Tweede primer', 'de polypurineketen (PPT), die RNase H laat liggen'],
        ['Eindproduct', 'lineair dsDNA met twee LTR\'s (U3-R-U5)'], ['Nauwkeurigheid', 'RT heeft geen proefleesfunctie → veel mutaties, dus snelle resistentie']],
      why: 'Reverse transcriptie draait het "gebruikelijke" DNA→RNA om en was het bewijs dat informatie ook terug kan stromen. Het verklaart waarom retrovirussen permanent in het genoom kunnen blijven, waarom hiv-behandelingen vaak RT als doelwit hebben, en het is de basis van de RT-stap in RT-qPCR en cDNA-technieken.',
    },
    en: {
      what: 'Retroviruses such as HIV-1 carry their genetic information as RNA but insert their hereditary material as DNA. Reverse transcriptase (RT) converts the single-stranded (+)RNA genome into double-stranded DNA. The same enzyme does three things: make DNA on an RNA template, make DNA on a DNA template, and degrade the copied RNA with its RNase H activity. HIV-1 mainly infects CD4⁺ T cells and macrophages; the process largely takes place inside the capsid in the cytoplasm.',
      how: [
        'A host tRNA (tRNA-Lys3) anneals to the primer binding site (PBS) of the genome and supplies the free 3\'-OH that RT starts from.',
        'RT extends to the 5\' end of the RNA: the short "minus-strand strong-stop" DNA containing R and U5.',
        'The RNase H activity degrades the copied R-U5 RNA, freeing the DNA end.',
        'First strand transfer: that DNA end contains a copy of R and therefore pairs with the R at the other end of the genome.',
        'RT now completes the whole (−) strand; RNase H clears the RNA away, except for one purine-rich piece: the polypurine tract (PPT).',
        'The PPT is left behind and serves as the primer for the (+) strand, which also copies part of the tRNA, creating the PBS sequence in DNA.',
        'The tRNA and the PPT are cut away; second strand transfer: the two PBS copies pair with each other.',
        'Both strands are completed: the product is linear dsDNA with a full LTR (U3-R-U5) at both ends — longer than the RNA it started from.',
      ],
      facts: [['Genome', '≈ 9.7 kb (+)ssRNA, two identical copies per virion'], ['Primer', 'host tRNA-Lys3 on the PBS'],
        ['Two RT activities', 'polymerase (RNA and DNA template) and RNase H'], ['Second primer', 'the polypurine tract (PPT), spared by RNase H'],
        ['Product', 'linear dsDNA with two LTRs (U3-R-U5)'], ['Fidelity', 'RT has no proofreading → many mutations, hence rapid resistance']],
      why: 'Reverse transcription reverses the "usual" DNA→RNA direction and proved that information can also flow back. It explains why retroviruses can stay in the genome permanently, why many HIV drugs target RT, and it is the basis of the RT step in RT-qPCR and cDNA methods.',
    },
    sources: [
      { t: 'Hu & Hughes, HIV-1 Reverse Transcription. Cold Spring Harb Perspect Med 2012;2:a006882', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3475395/' },
      { t: 'NIH HIVinfo, The HIV Life Cycle', url: 'https://hivinfo.nih.gov/understanding-hiv/fact-sheets/hiv-life-cycle' },
      { t: 'RCSB PDB 1RTD — catalytic complex of HIV-1 reverse transcriptase', url: 'https://www.rcsb.org/structure/1RTD' },
      { t: 'RCSB PDB 1HYS — HIV-1 RT in complex with a polypurine tract RNA:DNA', url: 'https://www.rcsb.org/structure/1HYS' },
    ],
  },

  integratie: {
    nl: {
      what: 'Integratie is de stap die een retrovirus permanent maakt: het virale enzym integrase bouwt het dubbelstrengige DNA uit de reverse transcriptie in een chromosoom van de gastheer in. Het ingebouwde virus heet een provirus en wordt daarna als een gewoon gen afgelezen en bij elke celdeling mee gekopieerd. Bij HIV-1 gebeurt dat niet willekeurig: de gastheerfactor LEDGF/p75 stuurt het complex naar transcriptioneel actieve genen.',
      how: [
        'Het virale dsDNA komt met het pre-integratiecomplex in de kern.',
        'Integrase bindt beide uiteinden van het virale DNA en houdt ze samen in één complex, het intasoom.',
        '3\'-processing: van elk 3\'-uiteinde knipt integrase twee nucleotiden af, zodat de streng eindigt op de geconserveerde CA-3\' met een vrije 3\'-OH.',
        'Strengoverdracht: die twee 3\'-OH-groepen vallen tegelijk het gastheer-DNA aan, op twee posities die 5 bp uit elkaar liggen, op tegenoverliggende strengen.',
        'Er blijven enkelstrengs gaten en losse 5\'-uiteinden over.',
        'Herstelenzymen van de gastheer vullen die aan; daardoor staat er aan weerszijden van het provirus 5 bp gastheersequentie dubbel.',
        'Het provirus ligt nu vast in het chromosoom, geflankeerd door twee LTR\'s; de linker-LTR werkt als promoter.',
        'RNA-polymerase II van de cel schrijft het provirus af. Blijft die promoter stil, dan is de cel latent besmet — het reservoir dat behandeling zo moeilijk maakt.',
      ],
      facts: [['Enzym', 'integrase (bij HIV-1 in het intasoom als tetrameer)'], ['3\'-processing', '2 nucleotiden per uiteinde weg → geconserveerde CA-3\''],
        ['Afstand tussen de insertiepunten', '5 bp bij HIV-1 (4 bp bij MLV)'], ['Gevolg', '5 bp duplicatie van gastheersequentie rond het provirus'],
        ['Gaten dichten', 'door herstelenzymen van de gastheer (welke precies is nog onduidelijk)'], ['Doelwitkeuze', 'LEDGF/p75 stuurt naar actieve genlichamen']],
      why: 'Integratie verklaart waarom een hiv-infectie levenslang is, waarom er een latent reservoir bestaat, en waarom integraseremmers (bv. dolutegravir) zo\'n belangrijke medicijnklasse zijn. Het is ook precies het verschil met het adenovirus uit het hoofdverhaal, dat episomaal blijft.',
    },
    en: {
      what: 'Integration is the step that makes a retrovirus permanent: the viral enzyme integrase inserts the double-stranded DNA produced by reverse transcription into a host chromosome. The inserted virus is called a provirus; from then on it is read like an ordinary gene and copied along at every cell division. In HIV-1 this does not happen at random: the host factor LEDGF/p75 steers the complex towards transcriptionally active genes.',
      how: [
        'The viral dsDNA enters the nucleus as part of the pre-integration complex.',
        'Integrase binds both ends of the viral DNA and holds them together in one complex, the intasome.',
        '3\' processing: integrase removes two nucleotides from each 3\' end, so the strand ends in the conserved CA-3\' with a free 3\'-OH.',
        'Strand transfer: those two 3\'-OH groups attack the host DNA simultaneously, at two positions 5 bp apart, on opposite strands.',
        'Single-stranded gaps and unjoined 5\' ends are left behind.',
        'Host repair enzymes fill them in, which duplicates 5 bp of host sequence on either side of the provirus.',
        'The provirus is now fixed in the chromosome, flanked by two LTRs; the left LTR acts as the promoter.',
        'The cell’s own RNA polymerase II transcribes the provirus. If that promoter stays silent, the cell is latently infected — the reservoir that makes treatment so hard.',
      ],
      facts: [['Enzyme', 'integrase (a tetramer in the HIV-1 intasome)'], ['3\' processing', '2 nucleotides removed per end → conserved CA-3\''],
        ['Spacing of the insertion points', '5 bp for HIV-1 (4 bp for MLV)'], ['Consequence', '5 bp duplication of host sequence flanking the provirus'],
        ['Gap repair', 'by host repair enzymes (exactly which ones is still unclear)'], ['Target choice', 'LEDGF/p75 directs integration to active gene bodies']],
      why: 'Integration explains why HIV infection is lifelong, why a latent reservoir exists, and why integrase inhibitors (e.g. dolutegravir) are such an important drug class. It is also precisely what distinguishes HIV from the adenovirus of the main story, which stays episomal.',
    },
    sources: [
      { t: 'Craigie & Bushman, HIV DNA Integration. Cold Spring Harb Perspect Med 2012;2:a006890', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3385939/' },
      { t: 'Engelman & Cherepanov, Retroviral Integrase Structure and DNA Recombination Mechanism. Microbiol Spectr 2014', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4334468/' },
      { t: 'RCSB PDB 5U1C — tetrameric HIV-1 strand transfer complex intasome', url: 'https://www.rcsb.org/structure/5U1C' },
      { t: 'RCSB PDB 3OS0 — PFV strand transfer complex (model voor strengoverdracht)', url: 'https://www.rcsb.org/structure/3OS0' },
    ],
  },

  kernimport: {
    nl: {
      what: 'Het kernporiecomplex (NPC) is de enige doorgang tussen cytoplasma en nucleoplasma. Het is een achtvoudig symmetrische structuur van ongeveer 110–120 MDa, gebouwd uit ~30 verschillende nucleoporinen die elk in veelvouden van acht voorkomen (samen ~500–1 000 eiwitmoleculen per porie). Het kanaal is gevuld met ongeordende FG-herhalingen die als een zeef werken: kleine moleculen glippen er passief doorheen, grotere alleen met een transportfactor. Een menselijke kern bevat er ongeveer 3 000.',
      how: [
        'Kleine moleculen tot ongeveer 40 kDa (~5 nm) diffunderen passief door het FG-netwerk.',
        'Grotere vracht draagt een kernlokalisatiesignaal (NLS), een kort stuk met veel basische aminozuren (bv. PKKKRKV van SV40).',
        'Importine α herkent de NLS en werkt als adapter; importine β bindt importine α en kan wél door de FG-zeef.',
        'Het complex "hopt" van FG-herhaling naar FG-herhaling door het kanaal — dat kost zelf geen ATP.',
        'In de kern bindt Ran·GTP aan importine β, waardoor de vracht loskomt.',
        'De importines gaan met Ran·GTP terug naar het cytoplasma, waar RanGAP het GTP hydrolyseert en ze weer vrijkomen.',
        'De richting komt dus van de Ran-gradiënt: RCC1 op het chromatine maakt Ran·GTP in de kern, RanGAP houdt het niveau buiten laag.',
        'Voor het adenovirus geldt een uitzondering: het capside (≈ 90 nm) past niet door het kanaal en wordt aan de porie ontmanteld, waarna alleen het DNA met proteïne VII naar binnen gaat.',
      ],
      facts: [['Massa NPC', '≈ 110–120 MDa (gewervelden)'], ['Nucleoporinen', '~30 soorten, ~500–1 000 moleculen per porie, achtvoudige symmetrie'],
        ['Centraal kanaal', '≈ 40 nm; buitendiameter 80–120 nm'], ['Passieve grens', '≈ 40 kDa / ~5 nm'],
        ['Poriën per kern', '≈ 3 000 (HeLa)'], ['Richtinggever', 'Ran·GTP-gradiënt: RCC1 in de kern, RanGAP in het cytoplasma']],
      why: 'Dit is hoofdstuk 4 van het verhaal: het punt waarop vreemd DNA daadwerkelijk bij het genoom komt. Dezelfde poort bepaalt ook de rest van het verhaal — transcriptiefactoren en polymerasen moeten naar binnen, rijp mRNA en ribosoomsubeenheden moeten naar buiten. Wie de kernporie begrijpt, begrijpt waarom eukaryoten transcriptie en translatie in ruimte én tijd kunnen scheiden.',
    },
    en: {
      what: 'The nuclear pore complex (NPC) is the only passage between cytoplasm and nucleoplasm. It is an eightfold symmetric structure of about 110–120 MDa, built from ~30 different nucleoporins each present in multiples of eight (together ~500–1,000 protein molecules per pore). The channel is filled with disordered FG repeats that act as a sieve: small molecules slip through passively, larger ones only with a transport factor. A human nucleus contains about 3,000 of them.',
      how: [
        'Small molecules up to about 40 kDa (~5 nm) diffuse passively through the FG meshwork.',
        'Larger cargo carries a nuclear localisation signal (NLS), a short stretch rich in basic amino acids (e.g. PKKKRKV from SV40).',
        'Importin α recognises the NLS and acts as an adaptor; importin β binds importin α and can pass the FG sieve.',
        'The complex "hops" from FG repeat to FG repeat through the channel — this step itself costs no ATP.',
        'Inside the nucleus Ran·GTP binds importin β, which releases the cargo.',
        'The importins return to the cytoplasm with Ran·GTP, where RanGAP hydrolyses the GTP and frees them again.',
        'Directionality therefore comes from the Ran gradient: RCC1 on chromatin makes Ran·GTP in the nucleus, RanGAP keeps the level low outside.',
        'The adenovirus is an exception: its capsid (≈ 90 nm) does not fit through the channel and is disassembled at the pore, after which only the DNA with protein VII goes in.',
      ],
      facts: [['NPC mass', '≈ 110–120 MDa (vertebrates)'], ['Nucleoporins', '~30 kinds, ~500–1,000 molecules per pore, eightfold symmetry'],
        ['Central channel', '≈ 40 nm; outer diameter 80–120 nm'], ['Passive limit', '≈ 40 kDa / ~5 nm'],
        ['Pores per nucleus', '≈ 3,000 (HeLa)'], ['Direction giver', 'Ran·GTP gradient: RCC1 in the nucleus, RanGAP in the cytoplasm']],
      why: 'This is chapter 4 of the story: the point where foreign DNA actually reaches the genome. The same gate governs the rest of the story — transcription factors and polymerases must get in, mature mRNA and ribosomal subunits must get out. Understanding the nuclear pore is understanding why eukaryotes can separate transcription and translation in space as well as time.',
    },
    sources: [
      { t: 'Alberts et al., The Transport of Molecules between the Nucleus and the Cytosol (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK26932/' },
      { t: 'Kabachinski & Schwartz, The nuclear pore complex — structure and function at a glance. J Cell Sci 2015;128:423–9', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4311126/' },
      { t: 'Beck & Hurt, The nuclear pore complex: understanding its function through structural insight. Nat Rev Mol Cell Biol 2017', url: 'https://www.nature.com/articles/nrm.2016.147' },
      { t: 'Trotman et al., Import of adenovirus DNA involves CAN/Nup214 and histone H1. Nat Cell Biol 2001', url: 'https://www.nature.com/articles/ncb1201-1092' },
      { t: 'RCSB PDB 7R5K — human nuclear pore complex (cryo-EM)', url: 'https://www.rcsb.org/structure/7R5K' },
    ],
  },
};
