/* Uitleg per knoop voor stage 'genome' (deel A: kern, nucleolus, chromosoom, chromatine, nucleosoom, histonmod, dnamethyl, gen) — zie app/SCENES.md */
const S = {
  albertsPack: { t: 'Alberts et al., Molecular Biology of the Cell (4e): Chromosomal DNA and Its Packaging in the Chromatin Fiber (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK26834/' },
  albertsGlobal: { t: 'Alberts et al., Molecular Biology of the Cell (4e): The Global Structure of Chromosomes (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK26847/' },
  albertsRNA: { t: 'Alberts et al., Molecular Biology of the Cell (4e): From DNA to RNA (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK26887/' },
  t2t: { t: 'Nurk et al. (2022) The complete sequence of a human genome. Science 376:44–53 (PubMed 35357919)', url: 'https://pubmed.ncbi.nlm.nih.gov/35357919/' },
  luger: { t: 'Luger et al. (1997) Crystal structure of the nucleosome core particle at 2.8 Å resolution. Nature 389:251–260 (PubMed 9305837)', url: 'https://pubmed.ncbi.nlm.nih.gov/9305837/' },
  davey: { t: 'Davey et al. (2002) Solvent mediated interactions in the structure of the nucleosome core particle at 1.9 Å resolution. J Mol Biol 319:1097–1113 (PDB 1KX5)', url: 'https://pubmed.ncbi.nlm.nih.gov/12079350/' },
  pdb1kx5: { t: 'RCSB PDB 1KX5 — Nucleosome core particle, NCP147, 1.9 Å', url: 'https://www.rcsb.org/structure/1KX5' },
  motm: { t: 'PDB-101 Molecule of the Month: Nucleosome', url: 'https://pdb101.rcsb.org/motm/7' },
  mcginty: { t: 'McGinty & Tan (2015) Nucleosome structure and function. Chem Rev 115:2255–2273 (PubMed 25495456)', url: 'https://pubmed.ncbi.nlm.nih.gov/25495456/' },
  ou: { t: 'Ou et al. (2017) ChromEMT: visualizing 3D chromatin structure and compaction in interphase and mitotic cells. Science 357:eaag0025 (PubMed 28751582)', url: 'https://pubmed.ncbi.nlm.nih.gov/28751582/' },
  rao: { t: 'Rao et al. (2014) A 3D map of the human genome at kilobase resolution reveals principles of chromatin looping. Cell 159:1665–1680 (PubMed 25497547)', url: 'https://pubmed.ncbi.nlm.nih.gov/25497547/' },
  fudenberg: { t: 'Fudenberg et al. (2016) Formation of chromosomal domains by loop extrusion. Cell Rep 15:2038–2049 (PubMed 27210764)', url: 'https://pubmed.ncbi.nlm.nih.gov/27210764/' },
  davidson: { t: 'Davidson et al. (2019) DNA loop extrusion by human cohesin. Science 366:1338–1345 (PubMed 31753851)', url: 'https://pubmed.ncbi.nlm.nih.gov/31753851/' },
  bannister: { t: 'Bannister & Kouzarides (2011) Regulation of chromatin by histone modifications. Cell Res 21:381–395 (PubMed 21321607)', url: 'https://pubmed.ncbi.nlm.nih.gov/21321607/' },
  saxonov: { t: 'Saxonov, Berg & Brutlag (2006) A genome-wide analysis of CpG dinucleotides in the human genome distinguishes two distinct classes of promoters. PNAS 103:1412–1417 (PubMed 16432200)', url: 'https://pubmed.ncbi.nlm.nih.gov/16432200/' },
  deaton: { t: 'Deaton & Bird (2011) CpG islands and the regulation of transcription. Genes Dev 25:1010–1022 (PubMed 21576262)', url: 'https://pubmed.ncbi.nlm.nih.gov/21576262/' },
  moore: { t: 'Moore, Le & Fan (2013) DNA methylation and its basic function. Neuropsychopharmacology 38:23–38 (PubMed 22781841)', url: 'https://pubmed.ncbi.nlm.nih.gov/22781841/' },
  jones: { t: 'Jones (2012) Functions of DNA methylation: islands, start sites, gene bodies and beyond. Nat Rev Genet 13:484–492 (PubMed 22641018)', url: 'https://pubmed.ncbi.nlm.nih.gov/22641018/' },
  tahiliani: { t: 'Tahiliani et al. (2009) Conversion of 5-methylcytosine to 5-hydroxymethylcytosine in mammalian DNA by MLL partner TET1. Science 324:930–935 (PubMed 19372391)', url: 'https://pubmed.ncbi.nlm.nih.gov/19372391/' },
  aubert: { t: 'Aubert et al. (2018) Pre-ribosomal RNA processing in human cells: from mechanisms to congenital diseases. Biomolecules 8:123 (PubMed 30356013)', url: 'https://pubmed.ncbi.nlm.nih.gov/30356013/' },
  nucleolusRev: { t: 'New insights into nucleolar structure and function. F1000Prime Rep 7:48 (2015) (PubMed 26097721)', url: 'https://pubmed.ncbi.nlm.nih.gov/26097721/' },
  delange: { t: 'de Lange (2005) Shelterin: the protein complex that shapes and safeguards human telomeres. Genes Dev 19:2100–2110 (PubMed 16166375)', url: 'https://pubmed.ncbi.nlm.nih.gov/16166375/' },
  altemose: { t: 'Altemose et al. (2022) Complete genomic and epigenetic maps of human centromeres. Science 376:eabl4178 (PubMed 35357911)', url: 'https://pubmed.ncbi.nlm.nih.gov/35357911/' },
  genecat: { t: 'Amaral et al. (2023) The status of the human gene catalogue. Nature 622:41–47 (PubMed 37794265)', url: 'https://pubmed.ncbi.nlm.nih.gov/37794265/' },
};

export default {
  kern: {
    nl: {
      kort: 'De celkern is de ruimte in de cel waar het DNA ligt. Twee membranen met poriën scheiden ze van de rest van de cel. Hier wordt het DNA afgelezen naar RNA, dat daarna via de poriën naar buiten gaat.',
      what: 'De celkern is het compartiment waarin het genoom van een menselijke cel ligt. Ze is omgeven door een dubbel membraan (de kernenvelop) met duizenden kernporiecomplexen, de enige doorgang tussen kern en cytoplasma. Binnenin liggen chromatine (DNA + eiwitten) en kernlichaampjes zoals de nucleolus, zonder eigen membraan.',
      how: [
        'De kernenvelop bestaat uit een binnen- en buitenmembraan; het buitenmembraan loopt door in het ruw ER.',
        'Aan de binnenkant ondersteunt de kernlamina (een netwerk van lamines) de envelop; heterochromatine ligt vaak tegen die lamina.',
        'Kernporiecomplexen laten kleine moleculen vrij door; grote eiwitten met een NLS worden actief geïmporteerd (importines, Ran-GTP-gradiënt).',
        'In de kern wordt DNA gerepliceerd en afgeschreven tot RNA; pre-mRNA wordt er gecapt, gesplicet en gepolyadenyleerd.',
        'Rijp mRNA en ribosoomsubeenheden worden via de kernporiën naar het cytoplasma geëxporteerd, waar de translatie gebeurt.',
        'In de nucleolus worden rRNA gemaakt en ribosoomsubeenheden geassembleerd.',
      ],
      facts: [['Diameter', '~5–10 µm (celtype-afhankelijk)'], ['Chromosomen', '46 (23 paren) in een lichaamscel'], ['DNA per diploïde cel', '~6 miljard bp ≈ 2 m'], ['Kernporiën', 'orde van duizenden per kern']],
      why: 'Door transcriptie (kern) en translatie (cytoplasma) ruimtelijk te scheiden kan een eukaryote cel RNA eerst bewerken en controleren voor het vertaald wordt. Daarom moet ook een DNA-virus zoals het adenovirus zijn genoom tot in de kern brengen.',
    },
    en: {
      kort: 'The nucleus is the space in the cell where the DNA is kept. Two membranes with pores separate it from the rest of the cell. Here the DNA is read into RNA, which then leaves through the pores.',
      what: 'The nucleus is the compartment that holds the genome of a human cell. It is surrounded by a double membrane (the nuclear envelope) with thousands of nuclear pore complexes, the only passage between nucleus and cytoplasm. Inside lie chromatin (DNA + proteins) and nuclear bodies such as the nucleolus, which have no membrane of their own.',
      how: [
        'The nuclear envelope consists of an inner and an outer membrane; the outer membrane is continuous with the rough ER.',
        'On the inside, the nuclear lamina (a network of lamins) supports the envelope; heterochromatin often lies against the lamina.',
        'Nuclear pore complexes let small molecules pass freely; large proteins with an NLS are actively imported (importins, Ran-GTP gradient).',
        'In the nucleus DNA is replicated and transcribed into RNA; pre-mRNA is capped, spliced and polyadenylated there.',
        'Mature mRNA and ribosomal subunits are exported through the nuclear pores to the cytoplasm, where translation takes place.',
        'In the nucleolus rRNA is made and ribosomal subunits are assembled.',
      ],
      facts: [['Diameter', '~5–10 µm (depends on cell type)'], ['Chromosomes', '46 (23 pairs) in a body cell'], ['DNA per diploid cell', '~6 billion bp ≈ 2 m'], ['Nuclear pores', 'on the order of thousands per nucleus']],
      why: 'By separating transcription (nucleus) and translation (cytoplasm) in space, a eukaryotic cell can process and check RNA before it is translated. That is also why a DNA virus such as adenovirus has to deliver its genome into the nucleus.',
    },
    sources: [S.albertsGlobal, S.albertsRNA, S.t2t, S.nucleolusRev],
  },

  nucleolus: {
    nl: {
      kort: 'De nucleolus is een dicht gebied in de kern zonder eigen membraan. Hier worden de meeste RNA\'s van het ribosoom gemaakt en samen met eiwitten tot de twee delen van het ribosoom gebouwd. Zonder nucleolus dus geen ribosomen, en geen eiwitten.',
      what: 'De nucleolus is het grootste lichaampje in de kern en heeft geen membraan. Hij vormt zich rond de rRNA-genen (rDNA) op de korte armen van de vijf acrocentrische chromosomen. Hier maakt RNA-polymerase I het rRNA en worden de subeenheden van het ribosoom opgebouwd.',
      how: [
        'rDNA ligt als honderden kop-aan-staart-herhalingen van ~43 kb (≈13 kb getranscribeerd + intergene spacer) op chromosomen 13, 14, 15, 21 en 22.',
        'RNA-polymerase I schrijft elke actieve eenheid met veel polymerasen tegelijk af ("kerstboom" in Miller-preparaten), aan de grens van fibrillair centrum (FC) en dicht fibrillair component (DFC).',
        'Het product is één 47S pre-rRNA met daarin 18S, 5.8S en 28S, gescheiden door spacers (5\'ETS, ITS1, ITS2, 3\'ETS).',
        'In de DFC modificeren snoRNP\'s het rRNA: box C/D-snoRNA\'s met fibrillarine (2\'-O-methylatie) en box H/ACA-snoRNA\'s met dyskerine (pseudouridine).',
        'Endo- en exonucleasen knippen de spacers weg; 18S wordt deel van de kleine subeenheid, 5.8S en 28S van de grote.',
        'Het 5S-rRNA wordt elders door RNA-polymerase III gemaakt en samen met ~80 geïmporteerde ribosomale eiwitten in het granulair component (GC) ingebouwd.',
        'Pre-40S en pre-60S worden apart via de kernporiën geëxporteerd (o.a. met CRM1/XPO1) en rijpen af in het cytoplasma.',
      ],
      facts: [['rDNA-kopieën', 'honderden per diploïde cel (vaak ~400; sterk variabel)'], ['Herhalingseenheid', '~43 kb, waarvan ~13 kb getranscribeerd'], ['Voorloper', '47S pre-rRNA → 18S + 5.8S + 28S'], ['Compartimenten', 'FC · DFC · GC'], ['Nucleoli per kern', 'meestal 1–3 (tot 10 NOR\'s)']],
      why: 'Ribosomen zijn de machines die mRNA vertalen. Een groeiende cel heeft er miljoenen nodig; rRNA vormt het grootste deel van al het RNA in de cel. Stoornissen in ribosoombiogenese veroorzaken ziekten (ribosomopathieën).',
    },
    en: {
      kort: 'The nucleolus is a dense region in the nucleus without its own membrane. Here most of the RNAs of the ribosome are made and assembled with proteins into the two parts of the ribosome. So without a nucleolus there are no ribosomes, and no proteins.',
      what: 'The nucleolus is the largest body in the nucleus and has no membrane. It forms around the rRNA genes (rDNA) on the short arms of the five acrocentric chromosomes. Here RNA polymerase I makes rRNA and the subunits of the ribosome are built.',
      how: [
        'rDNA lies as hundreds of head-to-tail repeats of ~43 kb (≈13 kb transcribed + intergenic spacer) on chromosomes 13, 14, 15, 21 and 22.',
        'RNA polymerase I transcribes each active unit with many polymerases at once ("Christmas tree" in Miller spreads), at the border of the fibrillar centre (FC) and dense fibrillar component (DFC).',
        'The product is one 47S pre-rRNA containing 18S, 5.8S and 28S, separated by spacers (5\'ETS, ITS1, ITS2, 3\'ETS).',
        'In the DFC snoRNPs modify the rRNA: box C/D snoRNAs with fibrillarin (2\'-O-methylation) and box H/ACA snoRNAs with dyskerin (pseudouridine).',
        'Endo- and exonucleases remove the spacers; 18S becomes part of the small subunit, 5.8S and 28S of the large one.',
        'The 5S rRNA is made elsewhere by RNA polymerase III and incorporated in the granular component (GC) together with ~80 imported ribosomal proteins.',
        'Pre-40S and pre-60S are exported separately through the nuclear pores (e.g. with CRM1/XPO1) and mature in the cytoplasm.',
      ],
      facts: [['rDNA copies', 'hundreds per diploid cell (often ~400; highly variable)'], ['Repeat unit', '~43 kb, of which ~13 kb is transcribed'], ['Precursor', '47S pre-rRNA → 18S + 5.8S + 28S'], ['Compartments', 'FC · DFC · GC'], ['Nucleoli per nucleus', 'usually 1–3 (up to 10 NORs)']],
      why: 'Ribosomes are the machines that translate mRNA. A growing cell needs millions of them; rRNA makes up most of all RNA in the cell. Defects in ribosome biogenesis cause diseases (ribosomopathies).',
    },
    sources: [S.aubert, S.nucleolusRev, S.t2t, S.albertsRNA],
  },

  chromosoom: {
    nl: {
      kort: 'Een chromosoom is één heel lange DNA-molecule, verpakt met eiwitten. Een menselijke lichaamscel heeft er 46, in paren. Vlak voor een celdeling is elk chromosoom gekopieerd en sterk opgevouwen, zodat elke dochtercel een volledige set krijgt.',
      what: 'Een chromosoom is één lange, lineaire DNA-molecule met de eiwitten die het verpakken. Een menselijke lichaamscel heeft 46 chromosomen: 22 paren autosomen en twee geslachtschromosomen (XX of XY). Na replicatie bestaat elk chromosoom uit twee identieke zusterchromatiden.',
      how: [
        'In de interfase is elk chromosoom ontvouwen tot chromatine en neemt het een eigen territorium in de kern in.',
        'In de S-fase wordt het DNA gerepliceerd; cohesine houdt de twee zusterchromatiden bij elkaar.',
        'Bij de mitose vouwt condensine elke chromatide tot een reeks lussen rond een as: het metafasechromosoom.',
        'In de profase verdwijnt cohesine van de armen; aan het centromeer blijft het (beschermd door shugoshin) tot separase het in de anafase knipt.',
        'Het centromeer (α-satelliet-DNA met CENP-A-nucleosomen) draagt het kinetochoor, waaraan de microtubuli van de spoelfiguur hechten.',
        'Telomeren (TTAGGG-herhalingen, bedekt door shelterin) beschermen de uiteinden; telomerase kan ze verlengen.',
      ],
      facts: [['Aantal', '46 (2n) · 23 per gameet'], ['Haploïd genoom', '≈ 3,05 Gb (T2T-CHM13)'], ['Grootste / kleinste', 'chr 1 ≈ 248 Mb · chr 21 ≈ 45 Mb'], ['Acrocentrisch', '13, 14, 15, 21, 22 (dragen rDNA)'], ['Telomeerherhaling', '5\'-TTAGGG-3\' (enkele tot ~15 kb)'], ['Centromeer', 'α-satelliet, monomeer 171 bp']],
      why: 'Chromosomen zorgen ervoor dat twee meter DNA georganiseerd, gekopieerd en eerlijk verdeeld wordt over de dochtercellen. Fouten in aantal of structuur (bv. trisomie 21) hebben grote gevolgen.',
    },
    en: {
      kort: 'A chromosome is one very long DNA molecule, packed with proteins. A human body cell has 46 of them, in pairs. Just before a cell divides, each chromosome has been copied and tightly folded, so that each daughter cell receives a complete set.',
      what: 'A chromosome is one long, linear DNA molecule together with the proteins that package it. A human body cell has 46 chromosomes: 22 pairs of autosomes and two sex chromosomes (XX or XY). After replication each chromosome consists of two identical sister chromatids.',
      how: [
        'In interphase each chromosome is unfolded into chromatin and occupies its own territory in the nucleus.',
        'In S phase the DNA is replicated; cohesin holds the two sister chromatids together.',
        'In mitosis condensin folds each chromatid into an array of loops around an axis: the metaphase chromosome.',
        'In prophase cohesin is removed from the arms; at the centromere it stays (protected by shugoshin) until separase cleaves it in anaphase.',
        'The centromere (α-satellite DNA with CENP-A nucleosomes) carries the kinetochore, to which the spindle microtubules attach.',
        'Telomeres (TTAGGG repeats covered by shelterin) protect the ends; telomerase can extend them.',
      ],
      facts: [['Number', '46 (2n) · 23 per gamete'], ['Haploid genome', '≈ 3.05 Gb (T2T-CHM13)'], ['Largest / smallest', 'chr 1 ≈ 248 Mb · chr 21 ≈ 45 Mb'], ['Acrocentric', '13, 14, 15, 21, 22 (carry rDNA)'], ['Telomere repeat', '5\'-TTAGGG-3\' (a few to ~15 kb)'], ['Centromere', 'α-satellite, 171 bp monomer']],
      why: 'Chromosomes make sure that two metres of DNA are organised, copied and fairly divided between the daughter cells. Errors in number or structure (e.g. trisomy 21) have major consequences.',
    },
    sources: [S.t2t, S.albertsGlobal, S.altemose, S.delange, S.albertsPack],
  },

  chromatine: {
    nl: {
      kort: 'Chromatine is DNA samen met de eiwitten die het verpakken. Zo past ongeveer twee meter DNA in een kern van enkele micrometer. Hoe strak het verpakt is, bepaalt mee welke genen kunnen worden afgelezen: open chromatine is actief, compact chromatine meestal stil.',
      what: 'Chromatine is het complex van DNA met eiwitten (vooral histonen) waarin het genoom in de kern verpakt zit. Het is geen statische verpakking: open euchromatine laat genen aflezen, compact heterochromatine houdt ze meestal stil. Op grotere schaal is chromatine georganiseerd in lussen, domeinen (TADs) en chromosoomterritoria.',
      how: [
        'DNA wikkelt rond histonoctameren tot nucleosomen, verbonden door linker-DNA: de 10 nm-vezel ("kralen aan een snoer").',
        'Histon H1 bindt waar het DNA het nucleosoom in- en uitgaat en helpt verdere compactie.',
        'In vitro vouwt de vezel tot een regelmatige 30 nm-vezel; in intacte kernen ziet men vooral een onregelmatige keten van 5–24 nm (ChromEMT).',
        'Cohesine extrudeert ATP-afhankelijk DNA-lussen tot het stopt bij CTCF-plaatsen in convergente oriëntatie; zo ontstaan lussen en TADs.',
        'In Hi-C-kaarten verschijnen TADs als driehoeken van verhoogd contact; ze helpen enhancers bij de juiste promoters te houden.',
        'Histonmodificaties en DNA-methylatie bepalen mee of een regio euchromatine (open) of heterochromatine (compact, bv. H3K9me3 + HP1) is.',
        'Elk chromosoom neemt in de interfase een eigen territorium in; heterochromatine ligt vaak aan de kernlamina en rond de nucleolus.',
      ],
      facts: [['DNA per cel', '~2 m in een kern van ~5–10 µm'], ['Nucleosoomherhaling', '~200 bp (147 bp kern + linker)'], ['10 nm-vezel', 'nucleosoom ≈ 11 nm breed'], ['Contactdomeinen (Hi-C)', 'mediaan ~185 kb; ~10 000 lussen'], ['CTCF-ankers', '>90 % convergent georiënteerd'], ['In-vivo-keten', '5–24 nm diameter (ChromEMT)']],
      why: 'Verpakking bepaalt toegankelijkheid: voordat een gen kan worden afgeschreven, moet zijn chromatine open zijn. Daarom is chromatine de brug tussen het genoom en genregulatie.',
    },
    en: {
      kort: 'Chromatin is DNA together with the proteins that pack it. This is how about two metres of DNA fits into a nucleus a few micrometres wide. How tightly it is packed helps decide which genes can be read: open chromatin is active, compact chromatin is mostly silent.',
      what: 'Chromatin is the complex of DNA with proteins (mainly histones) in which the genome is packed inside the nucleus. It is not static packaging: open euchromatin allows genes to be read, compact heterochromatin mostly keeps them silent. On a larger scale chromatin is organised into loops, domains (TADs) and chromosome territories.',
      how: [
        'DNA wraps around histone octamers to form nucleosomes, joined by linker DNA: the 10 nm fibre ("beads on a string").',
        'Histone H1 binds where the DNA enters and exits the nucleosome and helps further compaction.',
        'In vitro the fibre folds into a regular 30 nm fibre; in intact nuclei one mainly sees an irregular chain of 5–24 nm (ChromEMT).',
        'Cohesin extrudes DNA loops in an ATP-dependent way until it stops at CTCF sites in convergent orientation; this creates loops and TADs.',
        'In Hi-C maps TADs appear as triangles of increased contact; they help keep enhancers with the right promoters.',
        'Histone modifications and DNA methylation help decide whether a region is euchromatin (open) or heterochromatin (compact, e.g. H3K9me3 + HP1).',
        'In interphase each chromosome occupies its own territory; heterochromatin often lies at the nuclear lamina and around the nucleolus.',
      ],
      facts: [['DNA per cell', '~2 m in a nucleus of ~5–10 µm'], ['Nucleosome repeat', '~200 bp (147 bp core + linker)'], ['10 nm fibre', 'nucleosome ≈ 11 nm wide'], ['Contact domains (Hi-C)', 'median ~185 kb; ~10,000 loops'], ['CTCF anchors', '>90% in convergent orientation'], ['In vivo chain', '5–24 nm diameter (ChromEMT)']],
      why: 'Packaging determines accessibility: before a gene can be transcribed, its chromatin must be open. That makes chromatin the bridge between the genome and gene regulation.',
    },
    sources: [S.albertsPack, S.ou, S.rao, S.fudenberg, S.davidson],
  },

  nucleosoom: {
    nl: {
      kort: 'Het nucleosoom is de kleinste verpakkingseenheid van het DNA: een stukje DNA dat bijna twee keer rond een klosje van acht histoneiwitten gewikkeld is. Een lange rij nucleosomen vormt chromatine. Om een gen af te lezen moet het DNA er gedeeltelijk afgehaald of opgeschoven worden.',
      what: 'Het nucleosoom is de basiseenheid van chromatine. In het kerndeeltje ligt ~147 bp DNA in ongeveer 1,7 linkshandige superhelische windingen rond een octameer van histoneiwitten: twee kopieën van H2A, H2B, H3 en H4. Linker-DNA (en histon H1) verbindt opeenvolgende nucleosomen.',
      how: [
        'Elk kernhiston heeft een histonplooi: drie α-helices (α1–L1–α2–L2–α3). Twee histonen grijpen kop-aan-staart in elkaar ("handdruk"): H3 met H4, H2A met H2B.',
        'Twee H3–H4-paren vormen het (H3–H4)₂-tetrameer; dat bindt als eerste het centrale deel van het DNA.',
        'Daarna binden twee H2A–H2B-dimeren aan weerszijden: samen het octameer.',
        'Het DNA wordt vooral via de fosfaatruggengraat vastgehouden, op ~14 plaatsen waar de kleine groef naar het octameer wijst; arginines steken in de kleine groef.',
        'Omdat de contacten nauwelijks van de basen afhangen, kan het octameer bijna elke sequentie binden (wel met voorkeuren door DNA-buigbaarheid).',
        'De N-terminale staarten, rijk aan lysine en arginine, steken uit het deeltje en dragen posttranslationele modificaties.',
      ],
      facts: [['DNA in het kerndeeltje', '~147 bp (146 bp in 1AOI)'], ['Superhelix', '~1,65–1,7 linkshandige windingen'], ['Octameer', '2 × (H2A, H2B, H3, H4)'], ['Afmetingen', '~11 nm breed, ~5,5 nm hoog'], ['Linker-DNA', 'tientallen bp (typisch ~20–80)'], ['Structuur', 'PDB 1KX5 (1,9 Å), 1AOI (2,8 Å)']],
      why: 'Het nucleosoom is tegelijk verpakking en regelknop: het maakt DNA compact, maar ook minder toegankelijk. Remodelers en histonmodificaties verschuiven, openen of verwijderen nucleosomen om genen af te lezen.',
    },
    en: {
      kort: 'The nucleosome is the smallest packing unit of DNA: a piece of DNA wrapped almost twice around a spool of eight histone proteins. A long row of nucleosomes forms chromatin. To read a gene, the DNA has to be partly unwrapped or shifted.',
      what: 'The nucleosome is the basic unit of chromatin. In the core particle ~147 bp of DNA is wrapped in about 1.7 left-handed superhelical turns around an octamer of histone proteins: two copies each of H2A, H2B, H3 and H4. Linker DNA (and histone H1) connects consecutive nucleosomes.',
      how: [
        'Each core histone has a histone fold: three α-helices (α1–L1–α2–L2–α3). Two histones interlock head-to-tail ("handshake"): H3 with H4, H2A with H2B.',
        'Two H3–H4 pairs form the (H3–H4)₂ tetramer, which binds the central part of the DNA first.',
        'Then two H2A–H2B dimers bind on either side: together the octamer.',
        'The DNA is held mainly via the phosphate backbone, at ~14 sites where the minor groove faces the octamer; arginines insert into the minor groove.',
        'Because the contacts hardly depend on the bases, the octamer can bind almost any sequence (with preferences due to DNA bendability).',
        'The N-terminal tails, rich in lysine and arginine, stick out of the particle and carry post-translational modifications.',
      ],
      facts: [['DNA in the core particle', '~147 bp (146 bp in 1AOI)'], ['Superhelix', '~1.65–1.7 left-handed turns'], ['Octamer', '2 × (H2A, H2B, H3, H4)'], ['Dimensions', '~11 nm wide, ~5.5 nm high'], ['Linker DNA', 'tens of bp (typically ~20–80)'], ['Structure', 'PDB 1KX5 (1.9 Å), 1AOI (2.8 Å)']],
      why: 'The nucleosome is both packaging and control knob: it compacts DNA but also makes it less accessible. Remodellers and histone modifications slide, open or remove nucleosomes so that genes can be read.',
    },
    sources: [S.luger, S.davey, S.pdb1kx5, S.motm, S.mcginty],
  },

  histonmod: {
    nl: {
      kort: 'Histonen kunnen kleine chemische merktekens krijgen, vooral op hun uitstekende staarten. Sommige merktekens maken het chromatine losser, andere houden het dicht. Zo helpen ze bepalen welke genen aan of uit staan, zonder de DNA-code zelf te veranderen.',
      what: 'Histonen worden na de translatie chemisch gemodificeerd, vooral op hun N-terminale staarten: acetylatie, methylatie, fosforylatie, ubiquitinering en meer. Die merktekens veranderen de lading van de staart en vormen bindingsplaatsen voor andere eiwitten. Zo helpen ze bepalen of chromatine open (actief) of dicht (stil) is.',
      how: [
        'De H3-staart bevat veel lysines (o.a. K4, K9, K14, K18, K23, K27); de nummering telt vanaf het eerste residu na de verwijderde methionine.',
        '"Schrijvers" zetten merktekens: histonacetyltransferasen (HATs, bv. p300/CBP, GCN5) gebruiken acetyl-CoA; lysinemethyltransferasen gebruiken SAM.',
        'Acetylatie neutraliseert de positieve lading van lysine; dat verzwakt de contacten met het negatieve DNA en gaat samen met open, actief chromatine.',
        '"Wissers" halen merktekens weg: histondeacetylasen (HDACs) en lysinedemethylasen (bv. LSD1, JmjC-enzymen).',
        'Methylatie (me1, me2, me3) laat de lading intact; de betekenis hangt af van de positie: H3K4me3 bij actieve promoters, H3K9me3 in heterochromatine, H3K27me3 (PRC2/EZH2) bij Polycomb-uitschakeling.',
        '"Lezers" herkennen merktekens: bromodomeinen binden acetyl-lysine, chromodomeinen methyl-lysine (HP1 ↔ H3K9me3, Polycomb-CBX ↔ H3K27me3), PHD-vingers H3K4me3.',
        'Combinaties van merktekens worden samen gelezen: het idee van een "histoncode".',
      ],
      facts: [['Actief', 'H3K4me3 (promoter), H3K27ac (enhancer/promoter)'], ['Onderdrukkend', 'H3K9me3 (heterochromatine), H3K27me3 (Polycomb)'], ['Acetyldonor', 'acetyl-CoA'], ['Methyldonor', 'S-adenosylmethionine (SAM)'], ['Lezers', 'bromodomein · chromodomein · PHD-vinger']],
      why: 'Histonmodificaties vertalen signalen in een chromatinetoestand die genen aan- of uitzet en die bij celdeling (deels) wordt doorgegeven. Ze zijn het doelwit van geneesmiddelen, bv. HDAC-remmers bij kanker.',
    },
    en: {
      kort: 'Histones can receive small chemical marks, mainly on their protruding tails. Some marks loosen the chromatin, others keep it closed. In this way they help decide which genes are on or off, without changing the DNA code itself.',
      what: 'Histones are chemically modified after translation, mainly on their N-terminal tails: acetylation, methylation, phosphorylation, ubiquitination and more. These marks change the charge of the tail and create binding sites for other proteins. In this way they help determine whether chromatin is open (active) or closed (silent).',
      how: [
        'The H3 tail contains many lysines (e.g. K4, K9, K14, K18, K23, K27); numbering starts at the first residue after the removed methionine.',
        '"Writers" place marks: histone acetyltransferases (HATs, e.g. p300/CBP, GCN5) use acetyl-CoA; lysine methyltransferases use SAM.',
        'Acetylation neutralises the positive charge of lysine; this weakens contacts with the negative DNA and goes together with open, active chromatin.',
        '"Erasers" remove marks: histone deacetylases (HDACs) and lysine demethylases (e.g. LSD1, JmjC enzymes).',
        'Methylation (me1, me2, me3) leaves the charge intact; its meaning depends on the position: H3K4me3 at active promoters, H3K9me3 in heterochromatin, H3K27me3 (PRC2/EZH2) in Polycomb silencing.',
        '"Readers" recognise marks: bromodomains bind acetyl-lysine, chromodomains methyl-lysine (HP1 ↔ H3K9me3, Polycomb CBX ↔ H3K27me3), PHD fingers H3K4me3.',
        'Combinations of marks are read together: the idea of a "histone code".',
      ],
      facts: [['Active', 'H3K4me3 (promoter), H3K27ac (enhancer/promoter)'], ['Repressive', 'H3K9me3 (heterochromatin), H3K27me3 (Polycomb)'], ['Acetyl donor', 'acetyl-CoA'], ['Methyl donor', 'S-adenosylmethionine (SAM)'], ['Readers', 'bromodomain · chromodomain · PHD finger']],
      why: 'Histone modifications translate signals into a chromatin state that switches genes on or off and that is (partly) passed on at cell division. They are drug targets, e.g. HDAC inhibitors in cancer.',
    },
    sources: [S.bannister, S.mcginty, S.albertsPack],
  },

  dnamethyl: {
    nl: {
      kort: 'Bij DNA-methylatie krijgt een C in het DNA een kleine methylgroep. De letter en de basenparing blijven hetzelfde, maar eiwitten herkennen het merkteken. Een gemethyleerde promoter zet het gen meestal uit, en het patroon wordt bij elke celdeling doorgegeven.',
      what: 'Bij DNA-methylatie wordt een methylgroep op koolstof 5 van cytosine gezet (5-methylcytosine, 5mC). Bij zoogdieren gebeurt dat vooral in CpG-dinucleotiden. De basenparing verandert niet, maar het patroon wordt gelezen door eiwitten en helpt genen stabiel uit te schakelen.',
      how: [
        'CpG is palindroom: op beide strengen staat 5\'-CG-3\', dus een CpG-plaats kan op beide strengen gemethyleerd zijn.',
        'DNMT3A en DNMT3B (met DNMT3L) zetten de novo nieuwe methylgroepen, vooral tijdens de vroege ontwikkeling; de methyldonor is SAM.',
        'Na replicatie is het DNA hemigemethyleerd: de oude streng draagt de methylgroepen, de nieuwe niet.',
        'DNMT1 (met UHRF1, dat hemigemethyleerde CpG\'s herkent) kopieert het patroon op de nieuwe streng: onderhoudsmethylatie.',
        'De meeste CpG\'s in het genoom zijn gemethyleerd, maar CpG-eilanden in promoters meestal niet; een gemethyleerde promoter wordt stilgelegd.',
        'Methyl-CpG-bindende eiwitten (MBD-familie, MeCP2) lezen 5mC en rekruteren o.a. HDAC-complexen; methylatie kan ook de binding van transcriptiefactoren verhinderen.',
        'TET-enzymen oxideren 5mC tot 5hmC, 5fC en 5caC; TDG en base-excisieherstel vervangen die door C (actieve demethylatie). Passief verdwijnt methylatie als DNMT1 niet werkt tijdens replicatie.',
      ],
      facts: [['Merkteken', '5-methylcytosine (5mC) op C5'], ['Context', 'vooral CpG'], ['Gemethyleerde CpG\'s', 'meerderheid (~70–80 %) in lichaamscellen'], ['CpG-eilanden', 'in ~60–70 % van de promoters, meestal ongemethyleerd'], ['Enzymen', 'DNMT3A/B (de novo) · DNMT1 (onderhoud) · TET (oxidatie)']],
      why: 'DNA-methylatie is een erfelijk "geheugen" van genactiviteit: het houdt transposons, het inactieve X-chromosoom en ingeprente genen stil. Afwijkende methylatie (bv. van tumorsuppressorpromoters) komt vaak voor bij kanker.',
    },
    en: {
      kort: 'In DNA methylation a C in the DNA receives a small methyl group. The letter and the base pairing stay the same, but proteins recognise the mark. A methylated promoter usually switches the gene off, and the pattern is passed on at every cell division.',
      what: 'In DNA methylation a methyl group is added to carbon 5 of cytosine (5-methylcytosine, 5mC). In mammals this happens mainly in CpG dinucleotides. Base pairing does not change, but the pattern is read by proteins and helps to switch genes off stably.',
      how: [
        'CpG is palindromic: both strands read 5\'-CG-3\', so a CpG site can be methylated on both strands.',
        'DNMT3A and DNMT3B (with DNMT3L) place new methyl groups de novo, mainly during early development; the methyl donor is SAM.',
        'After replication the DNA is hemimethylated: the old strand carries the methyl groups, the new one does not.',
        'DNMT1 (with UHRF1, which recognises hemimethylated CpGs) copies the pattern onto the new strand: maintenance methylation.',
        'Most CpGs in the genome are methylated, but CpG islands in promoters usually are not; a methylated promoter is silenced.',
        'Methyl-CpG-binding proteins (MBD family, MeCP2) read 5mC and recruit e.g. HDAC complexes; methylation can also block transcription factor binding.',
        'TET enzymes oxidise 5mC to 5hmC, 5fC and 5caC; TDG and base excision repair replace these with C (active demethylation). Passively, methylation is lost when DNMT1 does not act during replication.',
      ],
      facts: [['Mark', '5-methylcytosine (5mC) on C5'], ['Context', 'mainly CpG'], ['Methylated CpGs', 'majority (~70–80%) in body cells'], ['CpG islands', 'in ~60–70% of promoters, usually unmethylated'], ['Enzymes', 'DNMT3A/B (de novo) · DNMT1 (maintenance) · TET (oxidation)']],
      why: 'DNA methylation is a heritable "memory" of gene activity: it keeps transposons, the inactive X chromosome and imprinted genes silent. Aberrant methylation (e.g. of tumour-suppressor promoters) is common in cancer.',
    },
    sources: [S.moore, S.deaton, S.saxonov, S.jones, S.tahiliani],
  },

  gen: {
    nl: {
      kort: 'Een gen is een stuk DNA dat wordt afgeschreven naar RNA, samen met de stukken die regelen wanneer dat gebeurt. Bij de mens bestaat een gen uit delen die in het mRNA blijven (exonen) en tussenstukken die eruit geknipt worden (intronen). Het gen is het startpunt van het hele verhaal van DNA naar eiwit.',
      what: 'Een gen is een stuk DNA dat tot een functioneel RNA wordt afgeschreven, samen met de regio\'s die dat regelen. Een typisch menselijk eiwitcoderend gen bestaat uit een promoter, exonen en (meestal veel langere) intronen, en eindigt met een polyadenylatiesignaal. Enhancers kunnen op grote afstand liggen.',
      how: [
        'Enhancers binden activerende transcriptiefactoren en bereiken de promoter via een DNA-lus (o.a. cohesine en Mediator).',
        'In de kernpromoter bouwt RNA-polymerase II met algemene transcriptiefactoren zijn startcomplex; sommige promoters hebben een TATA-box (~−30), veel liggen in een CpG-eiland.',
        'Transcriptie begint op de transcriptiestartplaats (+1) en loopt over exonen én intronen.',
        'Intronen beginnen bijna altijd met GT en eindigen met AG (GT–AG-regel); een vertakkingspunt-A ligt kort voor het 3\'-einde. Het spliceosoom knipt ze uit het pre-mRNA.',
        'Het eerste exon begint met de 5\'-UTR; de coderende sequentie (CDS) loopt van het startcodon ATG tot een stopcodon (TAA, TAG of TGA).',
        'Na het stopcodon volgt de 3\'-UTR met het signaal AATAAA; het RNA wordt ~10–30 nt verder geknipt en krijgt een poly(A)-staart.',
      ],
      facts: [['Eiwitcoderende genen (mens)', 'net geen 20 000'], ['Coderend deel van het genoom', '~1–1,5 %'], ['Intron-grenzen', 'GT … AG'], ['Stopcodons', 'TAA · TAG · TGA'], ['Poly(A)-signaal', 'AATAAA (AAUAAA in RNA)']],
      why: 'De architectuur van een gen bepaalt waar transcriptie begint en eindigt, welke delen in het mRNA terechtkomen en hoe het gereguleerd wordt. Alternatieve splicing laat één gen meerdere eiwitten maken.',
    },
    en: {
      kort: 'A gene is a stretch of DNA that is copied into RNA, together with the regions that control when this happens. In humans a gene consists of parts that stay in the mRNA (exons) and intervening pieces that are cut out (introns). The gene is the starting point of the whole story from DNA to protein.',
      what: 'A gene is a stretch of DNA that is transcribed into a functional RNA, together with the regions that control this. A typical human protein-coding gene consists of a promoter, exons and (usually much longer) introns, and ends with a polyadenylation signal. Enhancers can lie far away.',
      how: [
        'Enhancers bind activating transcription factors and reach the promoter through a DNA loop (involving cohesin and Mediator).',
        'At the core promoter RNA polymerase II builds its initiation complex with general transcription factors; some promoters have a TATA box (~−30), many lie in a CpG island.',
        'Transcription starts at the transcription start site (+1) and runs through exons and introns.',
        'Introns almost always start with GT and end with AG (GT–AG rule); a branch-point A lies shortly before the 3\' end. The spliceosome removes them from the pre-mRNA.',
        'The first exon starts with the 5\' UTR; the coding sequence (CDS) runs from the start codon ATG to a stop codon (TAA, TAG or TGA).',
        'After the stop codon comes the 3\' UTR with the signal AATAAA; the RNA is cleaved ~10–30 nt further on and receives a poly(A) tail.',
      ],
      facts: [['Protein-coding genes (human)', 'just under 20,000'], ['Coding part of the genome', '~1–1.5%'], ['Intron boundaries', 'GT … AG'], ['Stop codons', 'TAA · TAG · TGA'], ['Poly(A) signal', 'AATAAA (AAUAAA in RNA)']],
      why: 'The architecture of a gene determines where transcription starts and ends, which parts end up in the mRNA and how it is regulated. Alternative splicing lets one gene make several proteins.',
    },
    sources: [S.albertsRNA, S.genecat, S.deaton, S.rao],
  },
};
