/* Uitleg verhaallijn 2 (signalen): signaal, gpcr, steroid — zie app/SCENES.md */
const ALB = id => `https://www.ncbi.nlm.nih.gov/books/${id}/`;
const UNI = id => `https://www.uniprot.org/uniprotkb/${id}/entry`;

export default {
  signaal: {
    nl: {
      kort: 'Cellen sturen elkaar boodschappen met signaalmoleculen, zoals hormonen. Een cel reageert alleen als ze de passende [[receptor|receptor]] heeft. Sommige signalen binden buiten op de cel; vetoplosbare gaan door het membraan.',
      what: 'Cellen in een meercellig organisme sturen elkaar boodschappen met signaalmoleculen: hormonen, groeifactoren, neurotransmitters en lokale mediatoren. Een signaal werkt alleen op een cel die de passende receptor heeft; die bindt het signaal specifiek en zet het om in een reactie in de cel. Hydrofiele signalen (bv. de groeifactor EGF, een peptide, of adrenaline) kunnen niet door het membraan en binden een receptor op het celoppervlak. Kleine lipofiele signalen (bv. het steroïdhormoon cortisol) diffunderen door het membraan en binden een receptor in de cel.',
      how: [
        'Een cel toont alleen de receptoren waarvoor ze de genen afschrijft; daardoor reageren verschillende celtypes anders (of niet) op hetzelfde signaal.',
        'Het plasmamembraan is een lipidendubbellaag van ~5 nm met een hydrofobe kern: geladen of grote polaire moleculen (peptiden, catecholamines) kunnen er niet door.',
        'Receptoren op het celoppervlak vallen in drie grote klassen: ionkanaal-gekoppeld, G-eiwitgekoppeld (GPCR) en enzymgekoppeld (o.a. receptortyrosinekinasen, RTK).',
        'Voorbeeld RTK: EGF (53 aminozuren) bindt de EGF-receptor; twee receptoren dimeriseren en fosforyleren elkaars tyrosines.',
        'Voorbeeld GPCR: adrenaline bindt de β2-adrenerge receptor, die het G-eiwit Gs aanzet; zo ontstaat de tweede boodschapper cAMP.',
        'Voorbeeld kernreceptor: cortisol gaat door het membraan en bindt de glucocorticoïdreceptor (GR) in het cytosol; GR is zelf een transcriptiefactor.',
        'In de cel geven signaaleiwitten het signaal door en versterken het (kinasecascades, tweede boodschappers); veel van die eiwitten zijn moleculaire schakelaars die aan- en uitgaan door fosforylatie of GTP-binding.',
        'Om genexpressie te veranderen moet het signaal de kern bereiken: een kinase (bv. ERK, PKA) of de receptor zelf (GR) gaat de kern in en wijzigt de activiteit van transcriptiefactoren.',
      ],
      facts: [['Signaal → receptor', 'specifiek; alleen cellen met de receptor reageren'], ['Hydrofiel (EGF, adrenaline)', 'receptor op het celoppervlak'], ['Lipofiel (cortisol)', 'receptor in de cel (kernreceptor)'],
        ['EGF', '53 aminozuren (UniProt P01133)'], ['Adrenaline', 'catecholamine uit het bijniermerg (afgeleid van tyrosine)'], ['Cortisol', 'steroïdhormoon uit de bijnierschors (afgeleid van cholesterol)'],
        ['GPCR\'s in het menselijk genoom', '≈ 800 (grootste familie van membraanreceptoren)']],
      why: 'Dit is het begin van verhaal 2: een signaal van buiten zet een gen aan. We volgen EGF: via de EGF-receptor en de Ras–MAPK-cascade gaat het onmiddellijk-vroege gen FOS aan, en het eiwit dat we uiteindelijk maken is c-Fos. De zijpaden (GPCR/cAMP en de kernreceptor) tonen dat er meer dan één manier is om een signaal tot in de kern te krijgen.',
    },
    en: {
      kort: 'Cells send each other messages with signal molecules, such as hormones. A cell only responds if it has the matching [[receptor|receptor]]. Some signals bind on the outside of the cell; fat-soluble ones pass through the membrane.',
      what: 'Cells in a multicellular organism send each other messages with signal molecules: hormones, growth factors, neurotransmitters and local mediators. A signal only acts on a cell that has the matching receptor; the receptor binds the signal specifically and converts it into a response inside the cell. Hydrophilic signals (e.g. the growth factor EGF, a peptide, or adrenaline) cannot cross the membrane and bind a receptor on the cell surface. Small lipophilic signals (e.g. the steroid hormone cortisol) diffuse through the membrane and bind a receptor inside the cell.',
      how: [
        'A cell only displays the receptors whose genes it transcribes; so different cell types respond differently (or not at all) to the same signal.',
        'The plasma membrane is a ~5 nm lipid bilayer with a hydrophobic core: charged or large polar molecules (peptides, catecholamines) cannot cross it.',
        'Cell-surface receptors fall into three large classes: ion-channel-coupled, G protein-coupled (GPCR) and enzyme-coupled (including receptor tyrosine kinases, RTKs).',
        'RTK example: EGF (53 amino acids) binds the EGF receptor; two receptors dimerise and phosphorylate each other\'s tyrosines.',
        'GPCR example: adrenaline binds the β2-adrenergic receptor, which switches on the G protein Gs; this produces the second messenger cAMP.',
        'Nuclear receptor example: cortisol crosses the membrane and binds the glucocorticoid receptor (GR) in the cytosol; GR is itself a transcription factor.',
        'Inside the cell, signalling proteins relay and amplify the signal (kinase cascades, second messengers); many of these proteins are molecular switches turned on and off by phosphorylation or GTP binding.',
        'To change gene expression the signal must reach the nucleus: a kinase (e.g. ERK, PKA) or the receptor itself (GR) enters the nucleus and changes the activity of transcription factors.',
      ],
      facts: [['Signal → receptor', 'specific; only cells with the receptor respond'], ['Hydrophilic (EGF, adrenaline)', 'cell-surface receptor'], ['Lipophilic (cortisol)', 'intracellular receptor (nuclear receptor)'],
        ['EGF', '53 amino acids (UniProt P01133)'], ['Adrenaline', 'catecholamine from the adrenal medulla (derived from tyrosine)'], ['Cortisol', 'steroid hormone from the adrenal cortex (derived from cholesterol)'],
        ['GPCRs in the human genome', '≈ 800 (largest family of membrane receptors)']],
      why: 'This is the start of story 2: a signal from outside switches on a gene. We follow EGF: via the EGF receptor and the Ras–MAPK cascade the immediate early gene FOS is switched on, and the protein we finally make is c-Fos. The side paths (GPCR/cAMP and the nuclear receptor) show that there is more than one way to get a signal into the nucleus.',
    },
    sources: [
      { t: 'Alberts et al., Molecular Biology of the Cell (4e) — General Principles of Cell Communication (NCBI Bookshelf)', url: ALB('NBK26813') },
      { t: 'Alberts et al., Molecular Biology of the Cell (4e) — Signaling through Enzyme-Linked Cell-Surface Receptors (NCBI Bookshelf)', url: ALB('NBK26822') },
      { t: 'Alberts et al., Molecular Biology of the Cell (4e) — Signaling through G-Protein-Linked Cell-Surface Receptors (NCBI Bookshelf)', url: ALB('NBK26912') },
      { t: 'Oakley & Cidlowski (2013) The biology of the glucocorticoid receptor: new signaling mechanisms in health and disease. J Allergy Clin Immunol 132:1033 (PMC)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4084612/' },
      { t: 'Fredriksson et al. (2003) The G-protein-coupled receptors in the human genome form five main families. Mol Pharmacol 63:1256 (PubMed)', url: 'https://pubmed.ncbi.nlm.nih.gov/12761335/' },
      { t: 'UniProt P01133 — Pro-epidermal growth factor (EGF, mature chain 971–1023)', url: UNI('P01133') },
    ],
  },

  gpcr: {
    nl: {
      kort: 'Adrenaline bindt een [[receptor|receptor]] in het membraan, die een schakelaar-eiwit aanzet: het [[G-eiwit|g-eiwit]]. Daardoor maakt de cel het kleine boodschappermolecuul cAMP. Via een [[kinase|kinase]] zet dat uiteindelijk een gen in de kern aan.',
      what: 'G-eiwitgekoppelde receptoren (GPCR\'s) gaan 7 keer door het membraan en geven een signaal door via een heterotrimeer G-eiwit (α, β, γ). Het klassieke voorbeeld: adrenaline bindt de β2-adrenerge receptor, die Gs activeert. Gαs zet adenylylcyclase aan, dat ATP omzet in de tweede boodschapper cAMP. cAMP activeert proteïnekinase A (PKA); de katalytische subeenheden van PKA fosforyleren in de kern de transcriptiefactor CREB, die genen met een cAMP-responselement (CRE) aanzet.',
      how: [
        'Adrenaline bindt in een holte tussen de 7 transmembraanhelices van de β2-adrenerge receptor.',
        'De receptor verandert van vorm; de grootste beweging is het naar buiten zwaaien van het cytosolische uiteinde van helix 6, waardoor Gs kan binden.',
        'De actieve receptor werkt als GEF (guanine-nucleotide exchange factor): Gαs laat GDP los en bindt GTP.',
        'Gαs·GTP maakt zich los van Gβγ en activeert adenylylcyclase in het membraan: ATP → cAMP + PPᵢ.',
        'PKA is in rust een tetrameer van 2 regulatorische (R) en 2 katalytische (C) subeenheden. Elke R bindt 2 cAMP, waardoor de actieve C-subeenheden vrijkomen.',
        'Vrije C-subeenheden gaan de kern in en fosforyleren CREB op Ser133 (klassieke nummering).',
        'Fosfo-CREB bindt het KIX-domein van de co-activator CBP/p300; die acetyleert histonen en helpt het transcriptieapparaat. CREB zit als dimeer op het CRE (consensus TGACGTCA).',
        'Uitschakelen: Gαs hydrolyseert zelf zijn GTP (intrinsieke GTPase) en bindt opnieuw Gβγ; fosfodiësterasen breken cAMP af tot AMP; fosfatasen verwijderen het fosfaat van CREB.',
      ],
      facts: [['β2-adrenerge receptor (ADRB2)', '413 aa, 7 TM-helices (UniProt P07550)'], ['Structuur receptor + Gs', 'PDB 3SN6 (Rasmussen et al., 2011)'], ['Beweging helix 6 bij activatie', '≈ 14 Å naar buiten'],
        ['Gαs (GNAS)', '394 aa; bindt GDP (uit) of GTP (aan)'], ['PKA', 'R₂C₂; 4 cAMP maken 2 C vrij'], ['CREB-fosforylatie', 'Ser133 (isoform CREB-A, 341 aa; UniProt P16220 toont CREB-B, 327 aa: daar Ser119)'], ['CRE (consensus)', 'TGACGTCA']],
      why: 'Dit is een tweede manier om een signaal tot in de kern te brengen, naast de EGF → MAPK-route van het hoofdverhaal. Vergelijk: bij EGF zetten kinasen (ERK) het serum-responselement (SRE) aan, hier zet PKA het CRE aan. Het FOS-gen heeft beide elementen in zijn promoter (SRE en CRE), dus ook cAMP kan FOS aanzetten. Ongeveer een derde van de goedgekeurde geneesmiddelen werkt via GPCR\'s, bv. β2-agonisten bij astma.',
    },
    en: {
      kort: 'Adrenaline binds a [[receptor|receptor]] in the membrane, which switches on a switch protein: the [[G protein|g-eiwit]]. The cell then makes the small messenger molecule cAMP. Through a [[kinase|kinase]], this finally switches on a gene in the nucleus.',
      what: 'G protein-coupled receptors (GPCRs) cross the membrane 7 times and relay a signal via a heterotrimeric G protein (α, β, γ). The classic example: adrenaline binds the β2-adrenergic receptor, which activates Gs. Gαs switches on adenylyl cyclase, which converts ATP into the second messenger cAMP. cAMP activates protein kinase A (PKA); the catalytic subunits of PKA phosphorylate the transcription factor CREB in the nucleus, which switches on genes with a cAMP response element (CRE).',
      how: [
        'Adrenaline binds in a pocket between the 7 transmembrane helices of the β2-adrenergic receptor.',
        'The receptor changes shape; the largest movement is the outward swing of the cytosolic end of helix 6, which lets Gs bind.',
        'The active receptor acts as a GEF (guanine nucleotide exchange factor): Gαs releases GDP and binds GTP.',
        'Gαs·GTP separates from Gβγ and activates adenylyl cyclase in the membrane: ATP → cAMP + PPᵢ.',
        'At rest PKA is a tetramer of 2 regulatory (R) and 2 catalytic (C) subunits. Each R binds 2 cAMP, which releases the active C subunits.',
        'Free C subunits enter the nucleus and phosphorylate CREB on Ser133 (classic numbering).',
        'Phospho-CREB binds the KIX domain of the co-activator CBP/p300, which acetylates histones and helps the transcription machinery. CREB sits as a dimer on the CRE (consensus TGACGTCA).',
        'Switching off: Gαs hydrolyses its own GTP (intrinsic GTPase) and rebinds Gβγ; phosphodiesterases break cAMP down to AMP; phosphatases remove the phosphate from CREB.',
      ],
      facts: [['β2-adrenergic receptor (ADRB2)', '413 aa, 7 TM helices (UniProt P07550)'], ['Structure receptor + Gs', 'PDB 3SN6 (Rasmussen et al., 2011)'], ['Helix 6 movement on activation', '≈ 14 Å outward'],
        ['Gαs (GNAS)', '394 aa; binds GDP (off) or GTP (on)'], ['PKA', 'R₂C₂; 4 cAMP release 2 C'], ['CREB phosphorylation', 'Ser133 (isoform CREB-A, 341 aa; UniProt P16220 shows CREB-B, 327 aa: there Ser119)'], ['CRE (consensus)', 'TGACGTCA']],
      why: 'This is a second way to bring a signal into the nucleus, next to the EGF → MAPK route of the main story. Compare: with EGF, kinases (ERK) switch on the serum response element (SRE); here PKA switches on the CRE. The FOS gene has both elements in its promoter (SRE and CRE), so cAMP can also switch FOS on. About a third of approved drugs act via GPCRs, e.g. β2 agonists in asthma.',
    },
    sources: [
      { t: 'Alberts et al., Molecular Biology of the Cell (4e) — Signaling through G-Protein-Linked Cell-Surface Receptors (NCBI Bookshelf)', url: ALB('NBK26912') },
      { t: 'Rasmussen et al. (2011) Crystal structure of the β2 adrenergic receptor–Gs protein complex. Nature 477:549 (PubMed)', url: 'https://pubmed.ncbi.nlm.nih.gov/21772288/' },
      { t: 'RCSB PDB 3SN6 — β2 adrenergic receptor–Gs protein complex', url: 'https://www.rcsb.org/structure/3SN6' },
      { t: 'Kim, Cheng, Saldanha & Taylor (2007) PKA-I holoenzyme structure reveals a mechanism for cAMP-dependent activation. Cell 130:1032 (PubMed)', url: 'https://pubmed.ncbi.nlm.nih.gov/17889648/' },
      { t: 'Turnham & Scott (2016) Protein kinase A catalytic subunit isoform PRKACA; history, function and physiology. Gene 577:101 (PMC)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4713328/' },
      { t: 'Mayr & Montminy (2001) Transcriptional regulation by the phosphorylation-dependent factor CREB. Nat Rev Mol Cell Biol 2:599', url: 'https://www.nature.com/articles/35085068' },
      { t: 'Fisch, Prywes, Simon & Roeder (1989) Multiple sequence elements in the c-fos promoter mediate induction by cAMP. Genes Dev 3:198 (PubMed)', url: 'https://pubmed.ncbi.nlm.nih.gov/2541049/' },
      { t: 'Hauser et al. (2017) Trends in GPCR drug discovery: new agents, targets and indications. Nat Rev Drug Discov 16:829 (PubMed)', url: 'https://pubmed.ncbi.nlm.nih.gov/29075003/' },
      { t: 'UniProt P07550 — Beta-2 adrenergic receptor (ADRB2)', url: UNI('P07550') },
      { t: 'UniProt P16220 — CREB1', url: UNI('P16220') },
    ],
  },

  steroid: {
    nl: {
      kort: 'Cortisol is een hormoon dat oplost in vet en zo door het membraan gaat. Binnen bindt het zijn [[receptor|receptor]], die zelf naar de kern reist en daar genen aan- of uitzet. Zo is de receptor zelf de [[gen-schakelaar|transcriptiefactor]]: de kortste weg van signaal naar gen.',
      what: 'Steroïdhormonen zoals cortisol zijn klein en lipofiel: ze diffunderen door het plasmamembraan en binden een receptor in de cel. De glucocorticoïdreceptor (GR, gen NR3C1) hoort bij de superfamilie van de kernreceptoren: hij is tegelijk receptor en transcriptiefactor. Zonder hormoon zit GR in het cytosol in een complex met chaperones (Hsp90, p23, FKBP51). Na binding van cortisol verandert GR van vorm, laat het complex los, gaat de kern in en bindt als dimeer aan glucocorticoïd-responselementen (GRE\'s) in het DNA, waarna co-activatoren de transcriptie van doelgenen aanzetten.',
      how: [
        'Cortisol wordt in de bijnierschors uit cholesterol gemaakt en diffundeert als klein lipofiel molecule door de lipidendubbellaag.',
        'GR heeft drie hoofddomeinen: een N-terminaal transactivatiedomein (AF1), een DNA-bindend domein (DBD) met twee zinkvingers, en een ligandbindend domein (LBD, met AF2).',
        'Zonder hormoon houdt een chaperonecomplex (Hsp90-dimeer, p23, immunofilines zoals FKBP51) GR in een inactieve maar hormoonbindende vorm.',
        'Cortisol bindt in het LBD; GR verandert van vorm, het chaperonecomplex komt los en de kernlokalisatiesignalen (NL1, NL2) komen vrij.',
        'Importines herkennen NL1 en brengen GR via een kernporie de kern in.',
        'In de kern bindt GR als homodimeer aan een GRE: twee halve plaatsen van 6 bp met 3 bp ertussen (consensus GGAACAnnnTGTTCT). Elk DBD leest een halve plaats met zijn zinkvingers.',
        'GR rekruteert co-activatoren zoals de SRC-eiwitten (SRC-1 tot -3) en CBP/p300; die maken het chromatine toegankelijk en helpen RNA-polymerase II.',
        'Doelgenen zijn o.a. PEPCK en glucose-6-fosfatase (glucoseaanmaak in de lever). GR kan genen ook remmen, bv. door NF-κB en AP-1 te hinderen.',
      ],
      facts: [['Glucocorticoïdreceptor (NR3C1)', '777 aa, ≈ 86 kDa (UniProt P04150)'], ['DNA-bindend domein', 'aa 418–493, twee C4-zinkvingers'], ['Ligandbindend domein', 'aa 524–758'],
        ['GRE (consensus)', 'GGAACAnnnTGTTCT (2 × 6 bp, 3 bp tussenruimte)'], ['Chaperones in rust', 'Hsp90, Hsp70, p23, FKBP51/FKBP52'], ['Structuur GR-DBD op DNA', 'PDB 1R4R'],
        ['Ontstekingsremmers', 'synthetische glucocorticoïden (bv. dexamethason) werken via GR']],
      why: 'Dit zijpad is het kortste signaal naar de kern: geen tweede boodschapper of kinasecascade, want de receptor zelf is de transcriptiefactor. Het verbindt drie hoofdstukken: chaperones (Hsp90 houdt GR klaar), kernimport (NLS en importines) en genregulatie (co-activatoren op een responselement). Glucocorticoïden behoren tot de meest voorgeschreven geneesmiddelen tegen ontsteking.',
    },
    en: {
      kort: 'Cortisol is a hormone that dissolves in fat and so passes through the membrane. Inside, it binds its [[receptor|receptor]], which itself travels to the nucleus and switches genes on or off there. So the receptor itself is the [[gene switch|transcriptiefactor]]: the shortest route from signal to gene.',
      what: 'Steroid hormones such as cortisol are small and lipophilic: they diffuse through the plasma membrane and bind a receptor inside the cell. The glucocorticoid receptor (GR, gene NR3C1) belongs to the nuclear receptor superfamily: it is receptor and transcription factor at once. Without hormone, GR sits in the cytosol in a complex with chaperones (Hsp90, p23, FKBP51). After cortisol binds, GR changes shape, leaves the complex, enters the nucleus and binds as a dimer to glucocorticoid response elements (GREs) in the DNA, after which co-activators switch on transcription of target genes.',
      how: [
        'Cortisol is made from cholesterol in the adrenal cortex and, as a small lipophilic molecule, diffuses through the lipid bilayer.',
        'GR has three main domains: an N-terminal transactivation domain (AF1), a DNA-binding domain (DBD) with two zinc fingers, and a ligand-binding domain (LBD, with AF2).',
        'Without hormone, a chaperone complex (Hsp90 dimer, p23, immunophilins such as FKBP51) keeps GR in an inactive but hormone-binding shape.',
        'Cortisol binds in the LBD; GR changes shape, the chaperone complex comes off and the nuclear localisation signals (NL1, NL2) are exposed.',
        'Importins recognise NL1 and carry GR through a nuclear pore into the nucleus.',
        'In the nucleus GR binds a GRE as a homodimer: two 6-bp half-sites with 3 bp in between (consensus GGAACAnnnTGTTCT). Each DBD reads one half-site with its zinc fingers.',
        'GR recruits co-activators such as the SRC proteins (SRC-1 to -3) and CBP/p300; they open up chromatin and help RNA polymerase II.',
        'Target genes include PEPCK and glucose-6-phosphatase (glucose production in the liver). GR can also repress genes, e.g. by interfering with NF-κB and AP-1.',
      ],
      facts: [['Glucocorticoid receptor (NR3C1)', '777 aa, ≈ 86 kDa (UniProt P04150)'], ['DNA-binding domain', 'aa 418–493, two C4 zinc fingers'], ['Ligand-binding domain', 'aa 524–758'],
        ['GRE (consensus)', 'GGAACAnnnTGTTCT (2 × 6 bp, 3-bp spacer)'], ['Chaperones at rest', 'Hsp90, Hsp70, p23, FKBP51/FKBP52'], ['Structure GR DBD on DNA', 'PDB 1R4R'],
        ['Anti-inflammatory drugs', 'synthetic glucocorticoids (e.g. dexamethasone) act via GR']],
      why: 'This side path is the shortest signal to the nucleus: no second messenger or kinase cascade, because the receptor itself is the transcription factor. It links three chapters: chaperones (Hsp90 keeps GR ready), nuclear import (NLS and importins) and gene regulation (co-activators on a response element). Glucocorticoids are among the most prescribed anti-inflammatory drugs.',
    },
    sources: [
      { t: 'Oakley & Cidlowski (2013) The biology of the glucocorticoid receptor: new signaling mechanisms in health and disease. J Allergy Clin Immunol 132:1033 (PMC)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4084612/' },
      { t: 'Nicolaides, Chrousos & Kino, Glucocorticoid Receptor — Endotext (NCBI Bookshelf)', url: ALB('NBK279171') },
      { t: 'Schiller et al. (2014) Glucocorticoid receptor binds half sites as a monomer and regulates specific target genes. Genome Biol 15:418', url: 'https://genomebiology.biomedcentral.com/articles/10.1186/s13059-014-0418-y' },
      { t: 'Alberts et al., Molecular Biology of the Cell (4e) — General Principles of Cell Communication (NCBI Bookshelf)', url: ALB('NBK26813') },
      { t: 'Alberts et al., The Transport of Molecules between the Nucleus and the Cytosol (NCBI Bookshelf)', url: ALB('NBK26932') },
      { t: 'Freedman & Yamamoto (2004) Importin 7 and importin α/importin β are nuclear import receptors for the glucocorticoid receptor. Mol Biol Cell 15:2276 (PubMed)', url: 'https://pubmed.ncbi.nlm.nih.gov/15004228/' },
      { t: 'Davies, Ning & Sánchez (2002) A new first step in activation of steroid receptors: hormone-induced switching of FKBP51 and FKBP52 immunophilins. J Biol Chem 277:4597 (PubMed)', url: 'https://pubmed.ncbi.nlm.nih.gov/11751894/' },
      { t: 'UniProt P04150 — Glucocorticoid receptor (NR3C1)', url: UNI('P04150') },
      { t: 'RCSB PDB 1R4R — glucocorticoid receptor DNA-binding domain bound to DNA', url: 'https://www.rcsb.org/structure/1R4R' },
      { t: 'PDB-101 Molecule of the Month: Hsp90', url: 'https://pdb101.rcsb.org/motm/108' },
    ],
  },
};
