/* Uitleg verhaallijn 2 (signalen): rtk, mapk, srf — zie app/SCENES.md */
const ALB = 'https://www.ncbi.nlm.nih.gov/books/NBK26822/';
const S_ALB = { t: 'Alberts et al., Molecular Biology of the Cell (4e) — Signaling through Enzyme-Linked Cell-Surface Receptors (NCBI Bookshelf)', url: ALB };
const S_LEM = { t: 'Lemmon & Schlessinger (2010) Cell signaling by receptor tyrosine kinases. Cell 141:1117–1134', url: 'https://pubmed.ncbi.nlm.nih.gov/20602996/' };
const S_ROS = { t: 'Roskoski (2012) ERK1/2 MAP kinases: structure, function, and regulation. Pharmacol Res 66:105–143', url: 'https://doi.org/10.1016/j.phrs.2012.04.005' };

export default {
  rtk: {
    nl: {
      kort: 'Deze [[receptor|receptor]] in het membraan vangt de groeifactor EGF op. Twee receptoren vormen dan een paar en zetten fosfaat op elkaars staart ([[fosforylatie|fosforylatie]]). Op die fosfaten meren eiwitten aan die het signaal doorgeven aan de schakelaar Ras.',
      what: 'De EGF-receptor (EGFR, ook ErbB1 of HER1) is een receptortyrosinekinase: één eiwitketen met een extracellulair deel dat de groeifactor bindt, één transmembraanhelix en binnen in de cel een tyrosinekinasedomein met een lange C-terminale staart. Binding van EGF brengt twee receptoren samen; hun kinasedomeinen activeren elkaar en fosforyleren tyrosines in de staarten. Die fosfotyrosines zijn dockingplaatsen voor signaaleiwitten zoals Grb2.',
      how: [
        'EGF (53 aminozuren, drie disulfidebruggen) wordt uit een grote membraangebonden voorloper geknipt en bereikt de receptor van buitenaf.',
        'Zonder ligand is het extracellulaire deel "gesloten": een arm van domein II ligt vast tegen domein IV.',
        'EGF bindt tegelijk aan domein I en III. Het extracellulaire deel klapt open en de dimerisatie-arm van domein II komt vrij.',
        'Twee receptoren met EGF grijpen met die armen in elkaar: een rug-aan-rugdimeer (2 EGF : 2 receptoren). De twee EGF\'s raken elkaar niet – het dimeer wordt door de receptor zelf gevormd (PDB 1IVO).',
        'Binnen in de cel vormen de kinasedomeinen een asymmetrisch dimeer: de C-lob van het ene (activator) duwt tegen de N-lob van het andere (ontvanger), dat daardoor actief wordt (PDB 2GS2).',
        'De receptoren fosforyleren tyrosines in elkaars C-terminale staart (trans-autofosforylering) met ATP als fosfaatdonor.',
        'Het adaptereiwit Grb2 (SH3–SH2–SH3) bindt met zijn SH2-domein een fosfotyrosine (bv. Tyr1068). Zijn SH3-domeinen binden de prolinerijke staart van SOS.',
        'Zo komt SOS aan het membraan terecht, vlak bij Ras, dat daar met een lipide-anker aan het binnenblad hangt.',
      ],
      facts: [['EGF', '53 aa (UniProt P01133, rest 971–1023 van de voorloper)'], ['EGFR', '1210 aa incl. signaalpeptide (UniProt P00533)'], ['Grb2', '217 aa; SH3–SH2–SH3 (UniProt P62993)'],
        ['Stoichiometrie', '2 EGF : 2 EGFR'], ['Nummering Tyr', 'Tyr1068/1086 in de klassieke nummering = Tyr1092/1110 in UniProt'], ['3D', 'PDB 1IVO (EGF–EGFR), 2GS2 (kinasedimeer)']],
      why: 'Receptortyrosinekinasen vertalen een signaal buiten de cel naar fosfotyrosines binnenin. In verhaallijn 2 is dit de eerste stap op weg naar het FOS-gen. EGFR is ook medisch belangrijk: mutaties of overexpressie komen voor bij o.a. longkanker, en kinaseremmers (zoals gefitinib) en antilichamen (zoals cetuximab) zijn erop gericht.',
    },
    en: {
      kort: 'This [[receptor|receptor]] in the membrane catches the growth factor EGF. Two receptors then pair up and put phosphate on each other’s tail ([[phosphorylation|fosforylatie]]). Proteins dock on those phosphates and pass the signal on to the switch Ras.',
      what: 'The EGF receptor (EGFR, also ErbB1 or HER1) is a receptor tyrosine kinase: a single protein chain with an extracellular region that binds the growth factor, one transmembrane helix, and inside the cell a tyrosine kinase domain with a long C-terminal tail. EGF binding brings two receptors together; their kinase domains activate each other and phosphorylate tyrosines in the tails. These phosphotyrosines are docking sites for signalling proteins such as Grb2.',
      how: [
        'EGF (53 amino acids, three disulfide bonds) is cut from a large membrane-bound precursor and reaches the receptor from outside.',
        'Without ligand the extracellular region is "tethered": an arm of domain II is held against domain IV.',
        'EGF binds domains I and III at the same time. The extracellular region swings open and the dimerisation arm of domain II is exposed.',
        'Two EGF-bound receptors interlock with these arms: a back-to-back dimer (2 EGF : 2 receptors). The two EGFs do not touch – the dimer is formed by the receptor itself (PDB 1IVO).',
        'Inside the cell the kinase domains form an asymmetric dimer: the C-lobe of one (activator) presses against the N-lobe of the other (receiver), which becomes active (PDB 2GS2).',
        'The receptors phosphorylate tyrosines in each other\'s C-terminal tail (trans-autophosphorylation) with ATP as the phosphate donor.',
        'The adaptor protein Grb2 (SH3–SH2–SH3) binds a phosphotyrosine (e.g. Tyr1068) with its SH2 domain. Its SH3 domains bind the proline-rich tail of SOS.',
        'SOS thus ends up at the membrane, right next to Ras, which hangs from the inner leaflet by a lipid anchor.',
      ],
      facts: [['EGF', '53 aa (UniProt P01133, residues 971–1023 of the precursor)'], ['EGFR', '1210 aa incl. signal peptide (UniProt P00533)'], ['Grb2', '217 aa; SH3–SH2–SH3 (UniProt P62993)'],
        ['Stoichiometry', '2 EGF : 2 EGFR'], ['Tyr numbering', 'Tyr1068/1086 in the classical numbering = Tyr1092/1110 in UniProt'], ['3D', 'PDB 1IVO (EGF–EGFR), 2GS2 (kinase dimer)']],
      why: 'Receptor tyrosine kinases translate a signal outside the cell into phosphotyrosines inside it. In story 2 this is the first step towards the FOS gene. EGFR is also medically important: mutations or overexpression occur in e.g. lung cancer, and kinase inhibitors (such as gefitinib) and antibodies (such as cetuximab) target it.',
    },
    sources: [S_ALB, S_LEM,
      { t: 'Ogiso et al. (2002) Crystal structure of the complex of human epidermal growth factor and receptor extracellular domains. Cell 110:775–787 (PDB 1IVO)', url: 'https://www.rcsb.org/structure/1IVO' },
      { t: 'Zhang et al. (2006) An allosteric mechanism for activation of the kinase domain of epidermal growth factor receptor. Cell 125:1137–1149 (PDB 2GS2)', url: 'https://www.rcsb.org/structure/2GS2' },
      { t: 'UniProt P00533 — Epidermal growth factor receptor (human)', url: 'https://www.uniprot.org/uniprotkb/P00533/entry' },
      { t: 'UniProt P01133 — Pro-epidermal growth factor (human)', url: 'https://www.uniprot.org/uniprotkb/P01133/entry' },
      { t: 'UniProt P62993 — Growth factor receptor-bound protein 2 (human)', url: 'https://www.uniprot.org/uniprotkb/P62993/entry' }],
  },
  mapk: {
    nl: {
      kort: 'Ras is een aan/uit-schakelaar aan de binnenkant van het membraan. Eenmaal aan start het een kettingreactie van drie [[kinasen|kinase]] die elkaar aanzetten en zo het signaal versterken. Blijft Ras door een [[mutatie|mutatie]] vast aan, dan kan dat bijdragen tot kanker.',
      what: 'Ras is een klein GTPase: gebonden aan GTP staat het "aan", gebonden aan GDP "uit". SOS zet Ras aan; Ras-GTP start dan een cascade van drie kinasen – Raf (MAPKKK), MEK (MAPKK) en ERK (MAPK) – die elkaar achtereenvolgens fosforyleren. Actief ERK fosforyleert eiwitten in het cytosol en, na transport door de kernporiën, transcriptiefactoren in de kern.',
      how: [
        'Ras zit met een lipidestaart (farnesyl, bij sommige isovormen ook palmitoyl) aan het binnenblad van het plasmamembraan.',
        'SOS is een GEF (guanine nucleotide exchange factor): het doet GDP loskomen uit Ras. Omdat de cel veel meer GTP dan GDP bevat, bindt Ras daarna GTP.',
        'Ras-GTP bindt het Ras-bindende domein (RBD) van Raf en haalt Raf naar het membraan; daar wordt Raf actief (o.a. door dimerisatie en fosforylering).',
        'Raf fosforyleert MEK op twee serines in de activatielus (MEK1: Ser218 en Ser222).',
        'MEK is een dubbelspecifiek kinase: het fosforyleert ERK op de Thr én de Tyr van het Thr-Glu-Tyr-motief (TEY; ERK2: Thr185 en Tyr187). Pas met beide fosfaten is ERK volledig actief.',
        'Omdat één actief kinase na elkaar vele substraatmoleculen kan fosforyleren, wordt het signaal onderweg versterkt.',
        'Actief ERK gaat (deels) de kern in, via de kernporiën, en fosforyleert daar transcriptiefactoren zoals Elk-1.',
        'Uitschakelen: Ras hydrolyseert GTP zelf maar traag; GTPase-activerende eiwitten (GAP\'s, bv. neurofibromine/NF1) versnellen dat sterk. Fosfatasen (o.a. DUSP\'s/MKP\'s) halen de fosfaten van ERK weer af.',
      ],
      facts: [['Namen', 'Raf = MAPKKK · MEK = MAPKK · ERK = MAPK'], ['MEK1-activatie', 'fosfo-Ser218 + fosfo-Ser222'], ['ERK2-activatie', 'fosfo-Thr185 + fosfo-Tyr187 (TEY)'],
        ['Isovormen', 'H-, K-, N-Ras · A-, B-, C-Raf · MEK1/2 · ERK1/2'], ['RAS-mutaties bij kanker', '≈ 19 % van de kankerpatiënten (Prior et al., 2020)'], ['Typische RAS-hotspots', 'G12, G13, Q61']],
      why: 'De Ras–MAPK-route is een van de belangrijkste routes voor celgroei en -deling. Mutante Ras-eiwitten (vooral op G12, G13 en Q61) worden niet meer door GAP\'s uitgeschakeld en blijven in de GTP-vorm: de route staat dan permanent aan. Daarom zijn Ras, Raf (bv. BRAF V600E) en MEK belangrijke doelwitten voor kankergeneesmiddelen. In verhaallijn 2 brengt ERK het signaal tot bij het FOS-gen.',
    },
    en: {
      kort: 'Ras is an on/off switch on the inner side of the membrane. Once on, it starts a chain reaction of three [[kinases|kinase]] that switch each other on and so amplify the signal. If a [[mutation|mutatie]] locks Ras on, this can contribute to cancer.',
      what: 'Ras is a small GTPase: bound to GTP it is "on", bound to GDP "off". SOS switches Ras on; Ras-GTP then starts a cascade of three kinases – Raf (MAPKKK), MEK (MAPKK) and ERK (MAPK) – that phosphorylate each other in turn. Active ERK phosphorylates proteins in the cytosol and, after passing through the nuclear pores, transcription factors in the nucleus.',
      how: [
        'Ras is attached to the inner leaflet of the plasma membrane by a lipid tail (farnesyl, in some isoforms also palmitoyl).',
        'SOS is a GEF (guanine nucleotide exchange factor): it makes GDP come off Ras. Because the cell contains far more GTP than GDP, Ras then binds GTP.',
        'Ras-GTP binds the Ras-binding domain (RBD) of Raf and recruits Raf to the membrane, where Raf becomes active (e.g. through dimerisation and phosphorylation).',
        'Raf phosphorylates MEK on two serines in the activation loop (MEK1: Ser218 and Ser222).',
        'MEK is a dual-specificity kinase: it phosphorylates ERK on both the Thr and the Tyr of the Thr-Glu-Tyr motif (TEY; ERK2: Thr185 and Tyr187). Only with both phosphates is ERK fully active.',
        'Because one active kinase can phosphorylate many substrate molecules in turn, the signal is amplified along the way.',
        'Active ERK (partly) enters the nucleus through the nuclear pores and phosphorylates transcription factors such as Elk-1 there.',
        'Switching off: Ras hydrolyses GTP only slowly on its own; GTPase-activating proteins (GAPs, e.g. neurofibromin/NF1) speed this up greatly. Phosphatases (e.g. DUSPs/MKPs) remove the phosphates from ERK again.',
      ],
      facts: [['Names', 'Raf = MAPKKK · MEK = MAPKK · ERK = MAPK'], ['MEK1 activation', 'phospho-Ser218 + phospho-Ser222'], ['ERK2 activation', 'phospho-Thr185 + phospho-Tyr187 (TEY)'],
        ['Isoforms', 'H-, K-, N-Ras · A-, B-, C-Raf · MEK1/2 · ERK1/2'], ['RAS mutations in cancer', '≈ 19% of cancer patients (Prior et al., 2020)'], ['Typical RAS hotspots', 'G12, G13, Q61']],
      why: 'The Ras–MAPK pathway is one of the main pathways for cell growth and division. Mutant Ras proteins (mainly at G12, G13 and Q61) are no longer switched off by GAPs and stay in the GTP-bound form: the pathway is then permanently on. That is why Ras, Raf (e.g. BRAF V600E) and MEK are important targets for cancer drugs. In story 2, ERK carries the signal to the FOS gene.',
    },
    sources: [S_ALB, S_ROS,
      { t: 'Prior, Hood & Hartley (2020) The frequency of Ras mutations in cancer. Cancer Res 80:2969–2974', url: 'https://pubmed.ncbi.nlm.nih.gov/32209560/' },
      { t: 'UniProt Q02750 — Dual specificity MAPK kinase 1 (MEK1, human): phospho-Ser218/Ser222', url: 'https://www.uniprot.org/uniprotkb/Q02750/entry' },
      { t: 'UniProt P28482 — MAPK1/ERK2 (human): phospho-Thr185/Tyr187', url: 'https://www.uniprot.org/uniprotkb/P28482/entry' },
      { t: 'Pai et al. (1990) Refined crystal structure of the triphosphate conformation of H-ras p21 at 1.35 Å resolution. EMBO J 9:2351–2359 (PDB 5P21)', url: 'https://www.rcsb.org/structure/5P21' }],
  },
  srf: {
    nl: {
      kort: 'FOS is een gen dat binnen enkele minuten na een groeisignaal aangaat. De nodige [[gen-schakelaars|transcriptiefactor]] zitten al klaar op het DNA; ERK hoeft ze alleen een fosfaat te geven. Het eiwit c-Fos zet daarna zelf een volgende golf genen aan.',
      what: 'FOS is een onmiddellijk-vroeg gen (immediate early gene): het wordt binnen minuten na een groeisignaal afgeschreven, zonder dat daarvoor eerst nieuwe eiwitten gemaakt moeten worden. De schakelaar is het serum-responselement (SRE) ~300 bp vóór de startplaats: een CArG-box waarop een SRF-dimeer zit, met ernaast een Ets-plek voor de ternaire-complexfactor Elk-1. ERK fosforyleert Elk-1 en zet zo de transcriptie van FOS aan.',
      how: [
        'SRF (serum-responsfactor) bindt als dimeer aan de CArG-box, consensus CC(A/T)₆GG.',
        'Direct ernaast ligt een Ets-plek (kern GGA). Elk-1, een TCF uit de Ets-familie, bindt die plek op het FOS-SRE alleen samen met SRF: zijn B-box maakt contact met SRF. Samen vormen ze het ternaire complex (SRF–TCF–DNA).',
        'Dat complex zit er vaak al vóór het signaal; het wacht op fosforylering.',
        'Actief ERK koppelt aan Elk-1 en fosforyleert het C-terminale activatiedomein op meerdere plaatsen, o.a. Ser383 en Ser389.',
        'Gefosforyleerd Elk-1 bindt co-activatoren, o.a. het Mediator-complex via de subeenheid MED23 (Sur2), en CBP/p300. Mediator verbindt de activator met RNA-polymerase II aan de kernpromoter.',
        'Pol II schrijft FOS af: binnen minuten na het signaal is er FOS-(pre-)mRNA.',
        'Omdat alle nodige eiwitten al aanwezig zijn, gaat FOS ook aan als translatie geblokkeerd is (bv. met cycloheximide) – het kenmerk van een onmiddellijk-vroeg gen.',
        'Het c-Fos-eiwit vormt later met c-Jun het heterodimeer AP-1 (bZIP, leucineritssluiting). AP-1 bindt TRE-plaatsen (TGA(C/G)TCA) en zet verdere, latere genen aan.',
        'De respons is kort: fosfatasen zetten ERK en Elk-1 weer uit, en FOS-mRNA (AU-rijke elementen in de 3\'-UTR) en c-Fos-eiwit worden snel afgebroken.',
      ],
      facts: [['CArG-box', 'CC(A/T)₆GG'], ['Ets-kern', 'GGA(A/T)'], ['AP-1-plaats (TRE)', 'TGA(C/G)TCA'], ['Ligging SRE', '≈ −300 t.o.v. de startplaats van FOS'],
        ['Elk-1', '428 aa; P-Ser383, P-Ser389 (UniProt P19419)'], ['SRF · c-Fos', '508 aa (P11831) · 380 aa (P01100)'], ['Halfwaardetijd FOS-mRNA', '≈ 10–15 min'], ['Halfwaardetijd c-Fos-eiwit', '≈ 1,5–2 u (afhankelijk van celtype)']],
      why: 'Onmiddellijk-vroege genen zijn de eerste genen die op een groeisignaal reageren; hun producten (zoals c-Fos) zijn zelf transcriptiefactoren die een tweede golf van genen aanzetten. Zo wordt een kortstondig signaal omgezet in een langer durende verandering van genexpressie. In verhaallijn 2 volgen we nu het FOS-gen verder: promoter, transcriptie, processing, export en translatie tot het c-Fos-eiwit.',
    },
    en: {
      kort: 'FOS is a gene that switches on within minutes of a growth signal. The [[gene switches|transcriptiefactor]] it needs are already waiting on the DNA; ERK only has to give them a phosphate. The c-Fos protein then switches on a next wave of genes itself.',
      what: 'FOS is an immediate early gene: it is transcribed within minutes of a growth signal, without new proteins having to be made first. The switch is the serum response element (SRE) ~300 bp upstream of the start site: a CArG box bound by an SRF dimer, with an adjacent Ets site for the ternary complex factor Elk-1. ERK phosphorylates Elk-1 and thereby switches on FOS transcription.',
      how: [
        'SRF (serum response factor) binds the CArG box, consensus CC(A/T)₆GG, as a dimer.',
        'Right next to it lies an Ets site (core GGA). Elk-1, a TCF of the Ets family, binds this site on the FOS SRE only together with SRF: its B-box contacts SRF. Together they form the ternary complex (SRF–TCF–DNA).',
        'This complex is often already in place before the signal; it waits for phosphorylation.',
        'Active ERK docks onto Elk-1 and phosphorylates its C-terminal activation domain at several sites, including Ser383 and Ser389.',
        'Phosphorylated Elk-1 binds co-activators, including the Mediator complex via its MED23 (Sur2) subunit, and CBP/p300. Mediator connects the activator with RNA polymerase II at the core promoter.',
        'Pol II transcribes FOS: within minutes of the signal there is FOS (pre-)mRNA.',
        'Because all the proteins needed are already present, FOS also switches on when translation is blocked (e.g. with cycloheximide) – the hallmark of an immediate early gene.',
        'The c-Fos protein later forms the heterodimer AP-1 with c-Jun (bZIP, leucine zipper). AP-1 binds TRE sites (TGA(C/G)TCA) and switches on further, later genes.',
        'The response is brief: phosphatases switch ERK and Elk-1 off again, and FOS mRNA (AU-rich elements in the 3\' UTR) and c-Fos protein are degraded quickly.',
      ],
      facts: [['CArG box', 'CC(A/T)₆GG'], ['Ets core', 'GGA(A/T)'], ['AP-1 site (TRE)', 'TGA(C/G)TCA'], ['SRE position', '≈ −300 relative to the FOS start site'],
        ['Elk-1', '428 aa; P-Ser383, P-Ser389 (UniProt P19419)'], ['SRF · c-Fos', '508 aa (P11831) · 380 aa (P01100)'], ['FOS mRNA half-life', '≈ 10–15 min'], ['c-Fos protein half-life', '≈ 1.5–2 h (cell-type dependent)']],
      why: 'Immediate early genes are the first genes to respond to a growth signal; their products (such as c-Fos) are themselves transcription factors that switch on a second wave of genes. A brief signal is thus converted into a longer-lasting change in gene expression. In story 2 we now follow the FOS gene further: promoter, transcription, processing, export and translation up to the c-Fos protein.',
    },
    sources: [S_ALB,
      { t: 'Treisman (1986) Identification of a protein-binding site that mediates transcriptional response of the c-fos gene to serum factors. Cell 46:567–574', url: 'https://pubmed.ncbi.nlm.nih.gov/3524858/' },
      { t: 'Buchwalter, Gross & Wasylyk (2004) Ets ternary complex transcription factors. Gene 324:1–14', url: 'https://www.sciencedirect.com/science/article/abs/pii/S0378111903009557' },
      { t: 'Latinkic, Zeremski & Lau (1996) Elk-1 can recruit SRF to form a ternary complex upon the serum response element. Nucleic Acids Res 24:1345–1351', url: 'https://academic.oup.com/nar/article/24/7/1345/1058115' },
      { t: 'Thiel et al. (2021) Critical protein-protein interactions determine the biological activity of Elk-1, a master regulator of stimulus-induced gene transcription. Molecules 26:6125', url: 'https://pubmed.ncbi.nlm.nih.gov/34684708/' },
      { t: 'Stevens et al. (2002) Transcription control by E1A and MAP kinase pathway via Sur2 mediator subunit. Science 296:755–758', url: 'https://pubmed.ncbi.nlm.nih.gov/11934987/' },
      { t: 'Mo et al. (2001) Crystal structure of a ternary SAP-1/SRF/c-fos SRE DNA complex. J Mol Biol 314:495 (PDB 1K6O)', url: 'https://www.rcsb.org/structure/1K6O' },
      { t: 'Glover & Harrison (1995) Crystal structure of the heterodimeric bZIP transcription factor c-Fos–c-Jun bound to DNA. Nature 373:257–261 (PDB 1FOS)', url: 'https://www.rcsb.org/structure/1FOS' },
      { t: 'Shyu, Greenberg & Belasco (1989) The c-fos transcript is targeted for rapid decay by two distinct mRNA degradation pathways. Genes Dev 3:60–72', url: 'https://genesdev.cshlp.org/content/3/1/60.short' },
      { t: 'Reddy, Xie, Lindaman & Coss (2013) GnRH increases c-Fos half-life contributing to higher FSHβ induction. Mol Endocrinol 27:253–265 (c-Fos protein ≈ 100 min; FOS mRNA as short as ≈ 9 min)', url: 'https://academic.oup.com/mend/article/27/2/253/2615055' },
      { t: 'UniProt P19419 — ETS domain-containing protein Elk-1 (human)', url: 'https://www.uniprot.org/uniprotkb/P19419/entry' },
      { t: 'UniProt P01100 — Protein c-Fos (human)', url: 'https://www.uniprot.org/uniprotkb/P01100/entry' }],
  },
};
