/* Uitleg per knoop voor stage 'txn' — zie app/SCENES.md */
const S = {
  alberts_rna: { t: 'Alberts et al., Molecular Biology of the Cell, 4th ed. — From DNA to RNA (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK26887/' },
  alberts_motifs: { t: 'Alberts et al., MBoC 4th ed. — DNA-Binding Motifs in Gene Regulatory Proteins (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK26806/' },
  alberts_switch: { t: 'Alberts et al., MBoC 4th ed. — How Genetic Switches Work (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK26872/' },
  cooper_pol: { t: 'Cooper, The Cell, 2nd ed. — Eukaryotic RNA Polymerases and General Transcription Factors (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK9935/' },
  cooper_prok: { t: 'Cooper, The Cell, 2nd ed. — Transcription in Prokaryotes (NCBI Bookshelf)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK9850/' },
  hsin: { t: 'Hsin & Manley (2012) The RNA polymerase II CTD coordinates transcription and RNA processing. Genes Dev 26:2119 (PMC3465734)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3465734/' },
  jonkers: { t: 'Jonkers & Lis (2015) Getting up to speed with transcription elongation by RNA polymerase II. Nat Rev Mol Cell Biol 16:167', url: 'https://www.nature.com/articles/nrm3953' },
  core: { t: 'Core & Adelman (2019) Promoter-proximal pausing of RNA polymerase II: a nexus of gene regulation. Genes Dev 33:960 (PMC6672056)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6672056/' },
  tbp: { t: 'Kim, Nikolov & Burley (1993) Co-crystal structure of TBP recognizing the minor groove of a TATA element. Nature 365:520', url: 'https://www.nature.com/articles/365520a0' },
  roy: { t: 'Roy & Singer (2015) Core promoters in transcription: old problem, new insights. Trends Biochem Sci (PMC4340783)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4340783/' },
  deaton: { t: 'Deaton & Bird (2011) CpG islands and the regulation of transcription. Genes Dev 25:1010 (PubMed 21576262)', url: 'https://pubmed.ncbi.nlm.nih.gov/21576262/' },
  allen: { t: 'Allen & Taatjes (2015) The Mediator complex: a central integrator of transcription. Nat Rev Mol Cell Biol (PMC4963239)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4963239/' },
  merk: { t: 'Merkenschlager & Nora (2016) CTCF and cohesin in genome folding and transcriptional gene regulation. Annu Rev Genomics Hum Genet (PubMed 27089971)', url: 'https://pubmed.ncbi.nlm.nih.gov/27089971/' },
  pdb5flm: { t: 'RCSB PDB 5FLM — Structure of transcribing mammalian RNA polymerase II (Bernecky et al., Nature 2016)', url: 'https://www.rcsb.org/structure/5FLM' },
  pdb1i6h: { t: 'RCSB PDB 1I6H — RNA polymerase II elongation complex (Gnatt et al., Science 2001)', url: 'https://www.rcsb.org/structure/1I6H' },
  motm: { t: 'PDB-101 Molecule of the Month: RNA Polymerase', url: 'https://pdb101.rcsb.org/motm/40' },
  bushnell: { t: 'Bushnell, Cramer & Kornberg (2002) α-Amanitin–RNA polymerase II cocrystal at 2.8 Å. PNAS (PMC122170)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC122170/' },
  weinmann: { t: 'Weinmann, Raskas & Roeder (1974) Role of RNA polymerases II and III in transcription of the adenovirus genome. PNAS (PMC433786)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC433786/' },
  vannini: { t: 'Vannini & Cramer (2012) Conservation between the RNA polymerase I, II, and III transcription initiation machineries. Mol Cell 45:439 (PubMed 22365827)', url: 'https://pubmed.ncbi.nlm.nih.gov/22365827/' },
  schramm: { t: 'Schramm & Hernandez (2002) Recruitment of RNA polymerase III to its target promoters. Genes Dev 16:2593', url: 'https://genesdev.cshlp.org/content/16/20/2593.full' },
  schultz: { t: 'Schultz, Shields & Steitz (1991) Crystal structure of a CAP–DNA complex: the DNA is bent by 90 degrees. Science (PubMed 1653449)', url: 'https://pubmed.ncbi.nlm.nih.gov/1653449/' },
};

export default {
  transcriptie: {
    nl: {
      kort: 'Bij transcriptie maakt de cel een RNA-kopie van een gen. Het enzym [[RNA-polymerase|rnapol]] leest één DNA-streng af en bouwt er een passende RNA-streng tegenover. Dat RNA is de eerste stap van gen naar eiwit.',
      what: 'Transcriptie is het kopiëren van een gen naar RNA. RNA-polymerase II leest de matrijsstreng in de richting 3\'→5\' en bouwt het RNA 5\'→3\' op, telkens met een base die complementair is aan de matrijs. Het RNA heeft dus dezelfde sequentie als de coderende streng, met U in plaats van T.',
      how: [
        'Op de promoter bouwen algemene transcriptiefactoren en Pol II het preinitiatiecomplex op.',
        'TFIIH opent het DNA rond de startplaats: er ontstaat een transcriptiebel.',
        'Pol II koppelt ribonucleotiden (NTP\'s) aan het 3\'-OH van de groeiende keten; Mg²⁺ in het actieve centrum katalyseert de reactie.',
        'Slechts ~8–9 basen van het nieuwe RNA blijven gepaard met de matrijs (RNA–DNA-hybride); de rest verlaat het enzym via het uitgangskanaal.',
        'Na een pauze kort na de start wordt Pol II vrijgegeven (P-TEFb) en begint de productieve elongatie.',
        'Achter het enzym sluit de dubbelhelix weer; vóór het enzym ontstaan positieve supercoils die topo-isomerasen oplossen.',
        'Al tijdens de transcriptie wordt het pre-mRNA bewerkt (cap, splicing, 3\'-einde), aangestuurd via de CTD.',
      ],
      facts: [['Snelheid Pol II', '≈ 1–4 kb/min (≈ 15–65 nt/s), vaak ≈ 2 kb/min (≈ 35 nt/s)'], ['RNA–DNA-hybride', '≈ 8–9 bp'], ['CTD van Rpb1 (mens)', '52 × YSPTSPS'], ['Capping', 'als het RNA ≈ 20–30 nt lang is'], ['Richting', 'matrijs 3\'→5\' gelezen, RNA 5\'→3\' gemaakt']],
      why: 'Transcriptie is het eerste en sterkst gereguleerde punt van genexpressie: welke genen hoeveel RNA maken, bepaalt grotendeels welke eiwitten een cel heeft. In ons verhaal schrijft dezelfde Pol II ook de eiwitgenen van het adenovirus af.',
    },
    en: {
      kort: 'In transcription the cell makes an RNA copy of a gene. The enzyme [[RNA polymerase|rnapol]] reads one DNA strand and builds a matching RNA strand against it. This RNA is the first step from gene to protein.',
      what: 'Transcription is copying a gene into RNA. RNA polymerase II reads the template strand in the 3\'→5\' direction and builds the RNA 5\'→3\', each time with a base complementary to the template. The RNA therefore has the same sequence as the coding strand, with U instead of T.',
      how: [
        'At the promoter, general transcription factors and Pol II assemble the pre-initiation complex.',
        'TFIIH opens the DNA around the start site: a transcription bubble forms.',
        'Pol II joins ribonucleotides (NTPs) to the 3\'-OH of the growing chain; Mg²⁺ in the active site catalyses the reaction.',
        'Only ~8–9 bases of the new RNA stay paired with the template (RNA–DNA hybrid); the rest leaves the enzyme through the exit channel.',
        'After a pause shortly after the start, Pol II is released (P-TEFb) and productive elongation begins.',
        'Behind the enzyme the double helix closes again; ahead of it positive supercoils form, which topoisomerases relax.',
        'The pre-mRNA is already processed during transcription (cap, splicing, 3\' end), orchestrated via the CTD.',
      ],
      facts: [['Pol II speed', '≈ 1–4 kb/min (≈ 15–65 nt/s), often ≈ 2 kb/min (≈ 35 nt/s)'], ['RNA–DNA hybrid', '≈ 8–9 bp'], ['CTD of Rpb1 (human)', '52 × YSPTSPS'], ['Capping', 'when the RNA is ≈ 20–30 nt long'], ['Direction', 'template read 3\'→5\', RNA made 5\'→3\'']],
      why: 'Transcription is the first and most heavily regulated step of gene expression: which genes make how much RNA largely determines which proteins a cell has. In our story the same Pol II also transcribes the protein genes of the adenovirus.',
    },
    sources: [S.alberts_rna, S.jonkers, S.hsin, S.pdb5flm, S.motm],
  },

  genregulatie: {
    nl: {
      kort: 'Niet elk gen staat altijd aan. Schakelaar-eiwitten ([[transcriptiefactoren|transcriptiefactor]]) binden op het DNA en bepalen of en hoe sterk een gen wordt afgelezen. Zo verschilt een levercel van een zenuwcel, ook al hebben ze (bijna) hetzelfde DNA.',
      what: 'Genregulatie bepaalt of, wanneer en hoe sterk een gen wordt afgeschreven. Bij de mens gebeurt dat vooral via transcriptiefactoren die op enhancers en promoters binden, co-activatoren die het chromatine openen, en Mediator die het signaal doorgeeft aan RNA-polymerase II.',
      how: [
        'In compact chromatine zijn promoter en enhancer bedekt door nucleosomen; het gen staat stil.',
        'Een sequentiespecifieke activator bindt zijn motief in een enhancer, meestal met een α-helix in de grote groef (helix-turn-helix, zinkvinger, leucinerits, bHLH).',
        'Het activatiedomein rekruteert co-activatoren: histonacetyltransferasen (bv. p300/CBP) en ATP-afhankelijke remodelers (SWI/SNF) maken het chromatine toegankelijk.',
        'Mediator bindt het activatiedomein en vormt de brug naar Pol II en de algemene factoren.',
        'Een DNA-lus brengt de verre enhancer naast de promoter; CTCF en cohesine begrenzen zulke lusdomeinen.',
        'Repressoren op silencers rekruteren o.a. histondeacetylasen en werken dit tegen.',
        'Op de vrije promoter assembleert het preinitiatiecomplex: het gen is klaar om afgeschreven te worden.',
      ],
      facts: [['Afstand enhancer–promoter', 'kb tot honderden kb (soms ~1 Mb)'], ['Mediator (mens)', '26 kernsubeenheden + kinasemodule van 4'], ['Herkenning', 'meestal in de grote groef (randen van basenparen)'], ['Isolatoren', 'CTCF-plaatsen, samen met cohesine']],
      why: 'Alle cellen van een mens hebben (bijna) hetzelfde genoom; het verschil tussen een levercel en een neuron zit in welke genen aan staan. Fouten in transcriptiefactoren, enhancers of CTCF-grenzen liggen aan de basis van ontwikkelingsziekten en kanker.',
    },
    en: {
      kort: 'Not every gene is always on. Switch proteins ([[transcription factors|transcriptiefactor]]) bind to the DNA and decide whether and how strongly a gene is read. This is how a liver cell differs from a nerve cell, even though they have (almost) the same DNA.',
      what: 'Gene regulation decides whether, when and how strongly a gene is transcribed. In humans this happens mainly through transcription factors binding enhancers and promoters, co-activators that open chromatin, and Mediator, which passes the signal on to RNA polymerase II.',
      how: [
        'In compact chromatin the promoter and enhancer are covered by nucleosomes; the gene is silent.',
        'A sequence-specific activator binds its motif in an enhancer, usually with an α-helix in the major groove (helix-turn-helix, zinc finger, leucine zipper, bHLH).',
        'The activation domain recruits co-activators: histone acetyltransferases (e.g. p300/CBP) and ATP-dependent remodellers (SWI/SNF) make the chromatin accessible.',
        'Mediator binds the activation domain and forms the bridge to Pol II and the general factors.',
        'A DNA loop brings the distant enhancer next to the promoter; CTCF and cohesin delimit such loop domains.',
        'Repressors on silencers recruit e.g. histone deacetylases and counteract this.',
        'On the freed promoter the pre-initiation complex assembles: the gene is ready to be transcribed.',
      ],
      facts: [['Enhancer–promoter distance', 'kb to hundreds of kb (sometimes ~1 Mb)'], ['Mediator (human)', '26 core subunits + a 4-subunit kinase module'], ['Recognition', 'mostly in the major groove (base-pair edges)'], ['Insulators', 'CTCF sites, together with cohesin']],
      why: 'All cells of a person have (almost) the same genome; the difference between a liver cell and a neuron lies in which genes are switched on. Defects in transcription factors, enhancers or CTCF borders underlie developmental diseases and cancer.',
    },
    sources: [S.alberts_motifs, S.alberts_switch, S.allen, S.merk],
  },

  promoter: {
    nl: {
      kort: 'De promoter is het stukje DNA aan het begin van een gen waar het aflezen start. Daar zetten hulpeiwitten het enzym [[RNA-polymerase II|rnapol]] klaar. Hier wordt beslist of het gen wordt afgelezen.',
      what: 'De kernpromoter is het stukje DNA (~−40 tot +40 rond de startplaats) waar RNA-polymerase II met de algemene transcriptiefactoren (GTF\'s) het preinitiatiecomplex (PIC) vormt. Hij bevat korte motieven zoals BRE, TATA-box, Inr, MTE en DPE, maar geen enkel element komt in alle promoters voor.',
      how: [
        'TFIID bindt de promoter: TBP zit op de kleine groef van de TATA-box en buigt het DNA ~80°; TAF\'s herkennen Inr en DPE.',
        'TFIIA stabiliseert TBP op het DNA; TFIIB bindt de BRE-elementen en overbrugt naar Pol II.',
        'Pol II komt binnen samen met TFIIF; Mediator verbindt met activatoren op enhancers.',
        'TFIIE en TFIIH vervolledigen het (gesloten) PIC.',
        'De XPB-translocase van TFIIH opent het DNA (ATP): het open complex; de eerste nucleotiden worden gekoppeld.',
        'CDK7 (TFIIH) fosforyleert Ser5 van de CTD; Pol II verlaat de promoter (promoter escape).',
        'Na ~20–60 nt pauzeert Pol II (DSIF, NELF) tot P-TEFb (CDK9) NELF, DSIF en Ser2 fosforyleert: productieve elongatie.',
      ],
      facts: [['TATA-box', 'rond −31/−30 (consensus TATAWAWR)'], ['Inr', 'rond +1 (YYANWYY)'], ['DPE', '+28 tot +32'], ['DNA-buiging door TBP', '≈ 80°'], ['CpG-eilanden', 'bij ~70 % van de promoters; meestal TATA-loos'], ['Pauzeplaats', '≈ 20–60 nt na de start']],
      why: 'De promoter bepaalt waar en in welke richting transcriptie start. Het is het knooppunt waar alle regulatiesignalen (activatoren, chromatine, Mediator) samenkomen in één beslissing: vertrekt Pol II of niet?',
    },
    en: {
      kort: 'The promoter is the stretch of DNA at the start of a gene where reading begins. There, helper proteins set up the enzyme [[RNA polymerase II|rnapol]]. This is where it is decided whether the gene is read.',
      what: 'The core promoter is the stretch of DNA (~−40 to +40 around the start site) where RNA polymerase II forms the pre-initiation complex (PIC) with the general transcription factors (GTFs). It contains short motifs such as BRE, TATA box, Inr, MTE and DPE, but no single element occurs in all promoters.',
      how: [
        'TFIID binds the promoter: TBP sits on the minor groove of the TATA box and bends the DNA ~80°; TAFs recognise Inr and DPE.',
        'TFIIA stabilises TBP on the DNA; TFIIB binds the BRE elements and bridges to Pol II.',
        'Pol II arrives together with TFIIF; Mediator connects to activators on enhancers.',
        'TFIIE and TFIIH complete the (closed) PIC.',
        'The XPB translocase of TFIIH opens the DNA (ATP): the open complex; the first nucleotides are joined.',
        'CDK7 (TFIIH) phosphorylates Ser5 of the CTD; Pol II leaves the promoter (promoter escape).',
        'After ~20–60 nt Pol II pauses (DSIF, NELF) until P-TEFb (CDK9) phosphorylates NELF, DSIF and Ser2: productive elongation.',
      ],
      facts: [['TATA box', 'around −31/−30 (consensus TATAWAWR)'], ['Inr', 'around +1 (YYANWYY)'], ['DPE', '+28 to +32'], ['DNA bend by TBP', '≈ 80°'], ['CpG islands', 'at ~70 % of promoters; mostly TATA-less'], ['Pause site', '≈ 20–60 nt after the start']],
      why: 'The promoter decides where and in which direction transcription starts. It is the hub where all regulatory signals (activators, chromatin, Mediator) converge on one decision: does Pol II take off or not?',
    },
    sources: [S.cooper_pol, S.tbp, S.roy, S.deaton, S.core],
  },

  rnapol: {
    nl: {
      kort: 'RNA-polymerase II is het enzym dat in de kern alle genen voor eiwitten naar RNA kopieert. Het is een grote machine met een diepe kloof, waarin het DNA wordt gelezen en het RNA gebouwd. Een lange staart roept onderweg enzymen op die het RNA verder bewerken.',
      what: 'RNA-polymerase II (Pol II) is het enzym dat alle eiwitcoderende genen afschrijft. Het is een complex van 12 subeenheden (Rpb1–Rpb12, ≈ 0,5 MDa). De twee grootste, Rpb1 en Rpb2, vormen een diepe kloof met het actieve centrum; Rpb1 draagt bovendien de flexibele C-terminale staart (CTD).',
      how: [
        'Stroomafwaarts DNA komt de kloof binnen en wordt geopend; de beweeglijke klem sluit over het DNA.',
        'De matrijsstreng loopt naar het actieve centrum, waar een Mg²⁺-ion vastgehouden wordt door drie aspartaten (NADFDGD-motief van Rpb1).',
        'NTP\'s bereiken het actieve centrum via de trechter en het secundaire kanaal.',
        'De triggerlus sluit over een passende NTP; samen met de brughelix stuurt hij katalyse en translocatie met één basenpaar.',
        'Het RNA blijft ~8–9 bp gepaard (hybride) en verlaat het enzym via het RNA-uitgangskanaal, naast de Rpb4/7-stengel.',
        'De CTD (52 × YSPTSPS bij de mens) krijgt Ser5-P (CDK7) bij de start en Ser2-P (CDK9) tijdens elongatie en rekruteert zo capping-, splicing- en 3\'-eindfactoren.',
      ],
      facts: [['Subeenheden', '12 (Rpb1–Rpb12)'], ['Massa', '≈ 0,5 MDa'], ['CTD (mens)', '52 heptaden YSPTSPS'], ['Actief centrum', 'Mg²⁺ op Asp-lus NADFDGD (Rpb1)'], ['α-amanitine', 'bindt bij brughelix/triggerlus en blokkeert translocatie'], ['Structuren', '5FLM (zoogdier, 3,4 Å), 1I6H (gist, 10 subeenheden)']],
      why: 'Pol II is de structurele kern van genexpressie: bijna elke regulatiestap (Mediator, pauzeren, CTD-code) grijpt aan op dit ene enzym. Het is ook een doelwit van toxines (α-amanitine) en van virussen die hun genen door de cel laten afschrijven.',
    },
    en: {
      kort: 'RNA polymerase II is the enzyme in the nucleus that copies all genes for proteins into RNA. It is a large machine with a deep cleft, where the DNA is read and the RNA is built. A long tail calls in, along the way, enzymes that further process the RNA.',
      what: 'RNA polymerase II (Pol II) is the enzyme that transcribes all protein-coding genes. It is a complex of 12 subunits (Rpb1–Rpb12, ≈ 0.5 MDa). The two largest, Rpb1 and Rpb2, form a deep cleft containing the active site; Rpb1 also carries the flexible C-terminal tail (CTD).',
      how: [
        'Downstream DNA enters the cleft and is opened; the mobile clamp closes over the DNA.',
        'The template strand runs to the active site, where a Mg²⁺ ion is held by three aspartates (NADFDGD motif of Rpb1).',
        'NTPs reach the active site through the funnel and the secondary channel.',
        'The trigger loop closes over a matching NTP; together with the bridge helix it drives catalysis and translocation by one base pair.',
        'The RNA stays paired for ~8–9 bp (hybrid) and leaves through the RNA exit channel, next to the Rpb4/7 stalk.',
        'The CTD (52 × YSPTSPS in humans) gains Ser5-P (CDK7) at the start and Ser2-P (CDK9) during elongation, and thereby recruits capping, splicing and 3\'-end factors.',
      ],
      facts: [['Subunits', '12 (Rpb1–Rpb12)'], ['Mass', '≈ 0.5 MDa'], ['CTD (human)', '52 heptads YSPTSPS'], ['Active site', 'Mg²⁺ on the Asp loop NADFDGD (Rpb1)'], ['α-Amanitin', 'binds near bridge helix/trigger loop and blocks translocation'], ['Structures', '5FLM (mammal, 3.4 Å), 1I6H (yeast, 10 subunits)']],
      why: 'Pol II is the structural core of gene expression: almost every regulatory step (Mediator, pausing, the CTD code) acts on this one enzyme. It is also a target of toxins (α-amanitin) and of viruses that get their genes transcribed by the cell.',
    },
    sources: [S.pdb5flm, S.pdb1i6h, S.hsin, S.bushnell, S.motm],
  },

  operon: {
    nl: {
      kort: 'Bij bacteriën liggen genen voor één taak vaak samen in een operon, met één gedeelde aan/uit-schakelaar. Het lac-operon van de darmbacterie E. coli gaat pas volop aan als er lactose is en geen glucose. Het is het klassieke voorbeeld van hoe eiwitten genen aan- en uitzetten.',
      what: 'Bij bacteriën liggen genen met een gezamenlijke functie vaak in een operon: één promoter en operator sturen meerdere genen aan, die samen tot één polycistronisch mRNA worden afgeschreven. Het lac-operon van E. coli (lacZ, lacY, lacA) is het klassieke voorbeeld van een genschakelaar die op twee signalen reageert: lactose en glucose.',
      how: [
        'Bacteriën hebben één RNA-polymerase; de σ70-factor van het holo-enzym herkent de −35- (TTGACA) en −10-box (TATAAT), ~17 bp uit elkaar.',
        'Zonder lactose bindt de LacI-repressor (van het eigen lacI-gen) de operator en blokkeert transcriptie.',
        'Lactose wordt deels omgezet in allolactose; dat bindt LacI, die daardoor de operator loslaat.',
        'Is er ook glucose, dan is cAMP laag, bindt CAP niet en blijft de (zwakke) lac-promoter weinig actief.',
        'Zonder glucose stijgt cAMP; CAP–cAMP bindt vóór de promoter, buigt het DNA (~90°) en rekruteert RNA-polymerase: sterke transcriptie.',
        'Omdat er geen kern is, binden ribosomen het mRNA al terwijl het gemaakt wordt (gekoppelde transcriptie–translatie).',
      ],
      facts: [['Genen', 'lacZ (β-galactosidase), lacY (permease), lacA (transacetylase)'], ['σ70-consensus', '−35 TTGACA · −10 TATAAT'], ['Inductor', 'allolactose (of IPTG in het lab)'], ['Volledig aan', 'lactose aanwezig én glucose afwezig'], ['DNA-buiging door CAP', '≈ 90°']],
      why: 'Het lac-operon toonde (Jacob & Monod) voor het eerst dat genen door eiwitten aan- en uitgezet worden. De principes — repressoren, activatoren, DNA-buiging, combinatoriële logica — komen terug in de veel complexere menselijke genregulatie. Het lac-systeem wordt ook dagelijks gebruikt om eiwitten tot expressie te brengen (IPTG-inductie).',
    },
    en: {
      kort: 'In bacteria, genes for one task often lie together in an operon, with one shared on/off switch. The lac operon of the gut bacterium E. coli is only fully on when lactose is present and glucose is not. It is the classic example of how proteins switch genes on and off.',
      what: 'In bacteria, genes with a shared function often lie in an operon: one promoter and operator drive several genes, which are transcribed together into one polycistronic mRNA. The lac operon of E. coli (lacZ, lacY, lacA) is the classic example of a genetic switch that responds to two signals: lactose and glucose.',
      how: [
        'Bacteria have a single RNA polymerase; the σ70 factor of the holoenzyme recognises the −35 (TTGACA) and −10 (TATAAT) boxes, ~17 bp apart.',
        'Without lactose, the LacI repressor (from its own lacI gene) binds the operator and blocks transcription.',
        'Some lactose is converted into allolactose; it binds LacI, which then releases the operator.',
        'If glucose is also present, cAMP is low, CAP does not bind and the (weak) lac promoter stays barely active.',
        'Without glucose cAMP rises; CAP–cAMP binds upstream of the promoter, bends the DNA (~90°) and recruits RNA polymerase: strong transcription.',
        'Because there is no nucleus, ribosomes bind the mRNA while it is being made (coupled transcription–translation).',
      ],
      facts: [['Genes', 'lacZ (β-galactosidase), lacY (permease), lacA (transacetylase)'], ['σ70 consensus', '−35 TTGACA · −10 TATAAT'], ['Inducer', 'allolactose (or IPTG in the lab)'], ['Fully on', 'lactose present and glucose absent'], ['DNA bend by CAP', '≈ 90°']],
      why: 'The lac operon (Jacob & Monod) first showed that genes are switched on and off by proteins. Its principles — repressors, activators, DNA bending, combinatorial logic — return in the far more complex human gene regulation. The lac system is also used daily to express proteins (IPTG induction).',
    },
    sources: [S.cooper_prok, S.alberts_switch, S.schultz, S.alberts_rna],
  },

  polymerasen: {
    nl: {
      kort: 'Onze cellen hebben drie verwante enzymen die RNA maken, elk met een eigen taak. Pol I maakt de grote RNA’s van het [[ribosoom|ribosoom]], Pol II het mRNA en Pol III korte RNA’s zoals [[tRNA|trna]]. Een paddenstoelengif remt ze elk in andere mate, zodat je ze kunt onderscheiden.',
      what: 'De eukaryote kern heeft drie verwante RNA-polymerasen met een taakverdeling. Pol I maakt de grote rRNA\'s, Pol II de mRNA\'s en veel niet-coderende RNA\'s, Pol III korte stabiele RNA\'s zoals tRNA en 5S rRNA. Ze delen een geconserveerde kern en vijf identieke subeenheden, maar hebben elk hun eigen promoters en factoren.',
      how: [
        'Pol I (13 subeenheden bij de mens, 14 in gist) werkt in de nucleolus op de rDNA-herhalingen en maakt één 47S-voorloper, die via o.a. 45S wordt geknipt tot 18S, 5,8S en 28S rRNA; hij gebruikt UBF en SL1 (met TBP).',
        'Pol II (12 subeenheden) maakt mRNA, de meeste snRNA\'s, pri-miRNA\'s en lncRNA\'s; enkel Pol II heeft een CTD.',
        'Pol III (17 subeenheden) maakt tRNA\'s, 5S rRNA, U6 snRNA, 7SL- en 7SK-RNA en ook de VA-RNA\'s van het adenovirus.',
        'Pol III-promoters type 1 (5S: A-box, IE, C-box) en type 2 (tRNA: A- en B-box) liggen ín het gen; TFIIIC (en bij 5S eerst TFIIIA) plaatst TFIIIB stroomopwaarts, dat Pol III rekruteert.',
        'Type 3-promoters (U6, 7SK) liggen stroomopwaarts (DSE, PSE, TATA) en gebruiken SNAPc en TFIIIB.',
        'Pol III stopt op een reeks T\'s in de coderende streng.',
        'α-Amanitine onderscheidt ze: Pol II is zeer gevoelig, Pol III matig, Pol I resistent.',
      ],
      facts: [['Subeenheden (mens)', 'Pol I 13 · Pol II 12 · Pol III 17 (gist-Pol I: 14)'], ['Gedeeld door alle drie', '5 subeenheden (Rpb5, 6, 8, 10, 12)'], ['α-amanitine, 50 % remming (humane KB-cellen)', 'Pol II 0,02 µg/ml · Pol III 20 µg/ml · Pol I niet bij ≤ 200 µg/ml'], ['TBP', 'gebruikt door alle drie (in SL1, TFIID, TFIIIB)']],
      why: 'Ribosomen hebben enorme hoeveelheden rRNA en tRNA nodig; een aparte, gespecialiseerde machine voor die RNA\'s laat de cel groei en eiwitsynthese los van mRNA-regulatie sturen. Het α-amanitineverschil werd historisch gebruikt om te bepalen welk polymerase een gen afschrijft, bv. dat de VA-RNA\'s van het adenovirus van Pol III komen.',
    },
    en: {
      kort: 'Our cells have three related enzymes that make RNA, each with its own task. Pol I makes the large RNAs of the [[ribosome|ribosoom]], Pol II the mRNA and Pol III short RNAs such as [[tRNA|trna]]. A mushroom toxin blocks each of them to a different degree, so you can tell them apart.',
      what: 'The eukaryotic nucleus has three related RNA polymerases with a division of labour. Pol I makes the large rRNAs, Pol II the mRNAs and many non-coding RNAs, Pol III short stable RNAs such as tRNA and 5S rRNA. They share a conserved core and five identical subunits, but each has its own promoters and factors.',
      how: [
        'Pol I (13 subunits in humans, 14 in yeast) works in the nucleolus on the rDNA repeats and makes one 47S precursor, which is cut (via e.g. 45S) into 18S, 5.8S and 28S rRNA; it uses UBF and SL1 (with TBP).',
        'Pol II (12 subunits) makes mRNA, most snRNAs, pri-miRNAs and lncRNAs; only Pol II has a CTD.',
        'Pol III (17 subunits) makes tRNAs, 5S rRNA, U6 snRNA, 7SL and 7SK RNA and also the VA RNAs of adenovirus.',
        'Pol III promoters of type 1 (5S: A box, IE, C box) and type 2 (tRNA: A and B boxes) lie inside the gene; TFIIIC (for 5S first TFIIIA) places TFIIIB upstream, which recruits Pol III.',
        'Type 3 promoters (U6, 7SK) lie upstream (DSE, PSE, TATA) and use SNAPc and TFIIIB.',
        'Pol III terminates at a run of Ts in the coding strand.',
        'α-Amanitin tells them apart: Pol II is very sensitive, Pol III moderately, Pol I resistant.',
      ],
      facts: [['Subunits (human)', 'Pol I 13 · Pol II 12 · Pol III 17 (yeast Pol I: 14)'], ['Shared by all three', '5 subunits (Rpb5, 6, 8, 10, 12)'], ['α-Amanitin, 50 % inhibition (human KB cells)', 'Pol II 0.02 µg/ml · Pol III 20 µg/ml · Pol I not at ≤ 200 µg/ml'], ['TBP', 'used by all three (in SL1, TFIID, TFIIIB)']],
      why: 'Ribosomes need huge amounts of rRNA and tRNA; a separate, specialised machine for those RNAs lets the cell control growth and protein synthesis independently of mRNA regulation. The α-amanitin difference was historically used to find out which polymerase transcribes a gene, e.g. that the adenovirus VA RNAs come from Pol III.',
    },
    sources: [S.cooper_pol, S.vannini, S.schramm, S.weinmann],
  },
};
